# Generated by Django 3.2.12 on 2022-03-03 05:09

import ckeditor.fields
import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="AmendmentReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=125, verbose_name="Reason")),
            ],
            options={
                "verbose_name": "Application Amendment Reason",
                "verbose_name_plural": "Application Amendment Reasons",
            },
        ),
        migrations.CreateModel(
            name="CommunicationsLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.TextField(blank=True, verbose_name="To")),
                (
                    "fromm",
                    models.CharField(blank=True, max_length=200, verbose_name="From"),
                ),
                ("cc", models.TextField(blank=True, verbose_name="cc")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone Call"),
                            ("mail", "Mail"),
                            ("person", "In Person"),
                            ("onhold", "On Hold"),
                            ("onhold_remove", "Remove On Hold"),
                            ("with_qaofficer", "With QA Officer"),
                            ("with_qaofficer_completed", "QA Officer Completed"),
                            ("referral_complete", "Referral Completed"),
                        ],
                        default="email",
                        max_length=35,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subject / Description"
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("customer", models.IntegerField()),
                ("staff", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConservationCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="None", max_length=64)),
                ("label", models.CharField(default="None", max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="ConservationChangeCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="None", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="ConservationCriteria",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ConservationList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="None", max_length=64)),
                ("label", models.CharField(default="None", max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("role", models.CharField(max_length=32)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("PHS", "Perth Hills"),
                            ("SWC", "Swan Coastal"),
                            ("BWD", "Blackwood"),
                            ("WTN", "Wellington"),
                            ("DON", "Donnelly"),
                            ("FRK", "Frankland"),
                            ("ALB", "Albany"),
                            ("ESP", "Esperance"),
                            ("EKM", "East Kimberley"),
                            ("WKM", "West Kimberley"),
                            ("EXM", "Exmouth"),
                            ("PIL", "Pilbara"),
                            ("KAL", "Kalgoorlie"),
                            ("GER", "Geraldton"),
                            ("MOR", "Moora"),
                            ("SHB", "Shark Bay"),
                            ("GSN", "Great Southern"),
                            ("CWB", "Central Wheatbelt"),
                            ("SWB", "Southern Wheatbelt"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("credit_facility_link", "Credit Facility Link"),
                            ("deed_poll", "Deed poll"),
                            ("deed_poll_filming", "Deed poll Filming"),
                            ("deed_poll_event", "Deed poll Event"),
                            ("online_training_document", "Online Training Document"),
                            ("park_finder_link", "Park Finder Link"),
                            ("fees_and_charges", "Fees and charges link"),
                            ("event_fees_and_charges", "Event Fees and charges link"),
                            (
                                "commercial_filming_handbook",
                                "Commercial Filming Handbook link",
                            ),
                            ("park_stay_link", "Park Stay Link"),
                            (
                                "event_traffic_code_of_practice",
                                "Event traffic code of practice",
                            ),
                            ("trail_section_map", "Trail section map"),
                            ("dwer_application_form", "DWER Application Form"),
                        ],
                        max_length=255,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="GroupType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("flora", "Flora"),
                            ("fauna", "Fauna"),
                            ("community", "Community"),
                        ],
                        default=("fauna", "Fauna"),
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NameAuthority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("kimberley", "Kimberley"),
                            ("pilbara", "Pilbara"),
                            ("midwest", "Midwest"),
                            ("goldfields", "Goldfields"),
                            ("swan", "Swan"),
                            ("wheatbelt", "Wheatbelt"),
                            ("southwest", "South West"),
                            ("warren", "Warren"),
                            ("southcoast", "South Coast"),
                        ],
                        default=None,
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(default="None", max_length=128)),
                ("common_name", models.CharField(default="None", max_length=128)),
                ("name_currency", models.CharField(default="None", max_length=16)),
                ("image", models.CharField(default="None", max_length=512)),
                ("processing_status", models.CharField(default="None", max_length=512)),
                (
                    "district",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.district",
                    ),
                ),
                (
                    "group_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.grouptype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemMaintenance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "verbose_name_plural": "System maintenance",
            },
        ),
        migrations.CreateModel(
            name="ThreatCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="None", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="UserSystemSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(unique=True)),
                ("event_training_completed", models.BooleanField(default=False)),
                ("event_training_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "User System Settings",
            },
        ),
        migrations.CreateModel(
            name="ConservationAttributes",
            fields=[
                (
                    "general_management_advice",
                    models.CharField(default="None", max_length=512),
                ),
                (
                    "ecological_attributes",
                    models.CharField(default="None", max_length=512),
                ),
                (
                    "biological_attributes",
                    models.CharField(default="None", max_length=512),
                ),
                (
                    "specific_survey_advice",
                    models.CharField(default="None", max_length=512),
                ),
                (
                    "species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="boranga.species",
                    ),
                ),
                ("comments", models.CharField(default="None", max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name="ConservationStatus",
            fields=[
                (
                    "conservation_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="boranga.conservationlist",
                    ),
                ),
                (
                    "change_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.conservationchangecode",
                    ),
                ),
                (
                    "conservation_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.conservationcategory",
                    ),
                ),
                (
                    "conservation_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.conservationcriteria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "department_file_numbers",
                    models.CharField(default="None", max_length=512),
                ),
                ("community_original_area", models.IntegerField(default=-1)),
                ("community_original_area_accuracy", models.IntegerField(default=-1)),
                ("number_of_occurrences", models.IntegerField(default=-1)),
                ("extent_of_occurrences", models.IntegerField(default=-1)),
                ("area_of_occupancy", models.IntegerField(default=-1)),
                ("number_of_iucn_locations", models.IntegerField(default=-1)),
                (
                    "community_original_area_reference",
                    models.CharField(default="None", max_length=512),
                ),
                (
                    "species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="boranga.species",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxon", models.CharField(default="None", max_length=512)),
                ("taxon_id", models.IntegerField(default=-1)),
                ("previous_name", models.CharField(default="None", max_length=512)),
                ("family", models.CharField(default="None", max_length=512)),
                ("genus", models.CharField(default="None", max_length=512)),
                (
                    "phylogenetic_group",
                    models.CharField(default="None", max_length=512),
                ),
                (
                    "name_authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.nameauthority",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeciesDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.CharField(default="None", max_length=512)),
                (
                    "document_description",
                    models.CharField(default="None", max_length=1024),
                ),
                ("date_time", models.DateField(default=datetime.date.today)),
                (
                    "document_category",
                    models.ForeignKey(
                        default="None",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.documentcategory",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.species",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpeciesAttributes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_reference", models.CharField(default="None", max_length=128)),
                ("genetic", models.CharField(default="None", max_length=128)),
                ("biology", models.CharField(default="None", max_length=128)),
                ("ecology", models.CharField(default="None", max_length=128)),
                ("fire", models.CharField(default="None", max_length=128)),
                ("disease", models.CharField(default="None", max_length=128)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.species",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="species",
            name="taxonomy",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="boranga.taxonomy"
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="boranga.region"
            ),
        ),
        migrations.CreateModel(
            name="ConservationThreat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threat_description",
                    models.CharField(default="None", max_length=512),
                ),
                ("comment", models.CharField(default="None", max_length=512)),
                ("document", models.CharField(default="None", max_length=1024)),
                ("source", models.CharField(default="None", max_length=1024)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.species",
                    ),
                ),
                (
                    "threat_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.threatcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConservationPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="None", max_length=512)),
                ("comment", models.CharField(default="None", max_length=512)),
                ("source", models.CharField(default="None", max_length=1024)),
                (
                    "district",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.district",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.region",
                    ),
                ),
                ("species", models.ManyToManyField(to="boranga.Species")),
            ],
        ),
        migrations.CreateModel(
            name="CommitteeMeeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=128)),
                ("attendees", models.ManyToManyField(to="boranga.Contact")),
                ("species", models.ManyToManyField(to="boranga.Species")),
            ],
        ),
        migrations.AddField(
            model_name="species",
            name="conservation_status",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="boranga.conservationstatus",
            ),
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("community_name", models.CharField(default="None", max_length=2048)),
                ("community_id", models.IntegerField(default=-1)),
                ("community_status", models.CharField(default="None", max_length=128)),
                (
                    "district",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.district",
                    ),
                ),
                (
                    "group_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.grouptype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.region",
                    ),
                ),
                ("species", models.ManyToManyField(to="boranga.Species")),
                (
                    "conservation_status",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boranga.conservationstatus",
                    ),
                ),
            ],
        ),
    ]
