# Generated by Django 3.2.12 on 2022-02-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationcategory',
            name='code',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='conservationcriteria',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='conservationlist',
            name='code',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.CharField(choices=[('flora', 'Flora'), ('fauna', 'Fauna'), ('community', 'Community')], default=('fauna', 'Fauna'), max_length=64),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
