# Generated by Django 3.2.4 on 2021-12-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
