# Generated by Django 3.2.4 on 2022-01-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0002_alter_proposaltype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('flora', 'Flora'), ('fauna', 'Fauna'), ('community', 'Community')], default='1', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(default='None', max_length=128)),
                ('common_name', models.CharField(default='None', max_length=128)),
                ('name_currency', models.CharField(default='None', max_length=512)),
                ('region', models.IntegerField(default=-1)),
                ('district', models.IntegerField(default=-1)),
                ('image', models.CharField(default='None', max_length=512)),
                ('processing_status', models.CharField(default='None', max_length=512)),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.grouptype')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon', models.CharField(default='None', max_length=512)),
                ('taxon_id', models.IntegerField()),
                ('previous_name', models.CharField(default='None', max_length=512)),
                ('family', models.CharField(default='None', max_length=512)),
                ('genus', models.CharField(default='None', max_length=512)),
                ('phylogenetic_group', models.CharField(default='None', max_length=512)),
                ('name_authority', models.CharField(default='None', max_length=512)),
                ('community_id', models.CharField(default='None', max_length=512)),
                ('community_number', models.IntegerField(default=-1)),
                ('community_description', models.CharField(default='None', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationAttributes',
            fields=[
                ('general_management_advice', models.CharField(default='None', max_length=512)),
                ('ecological_attributes', models.CharField(default='None', max_length=512)),
                ('biological_attributes', models.CharField(default='None', max_length=512)),
                ('specific_survey_advice', models.CharField(default='None', max_length=512)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boranga.species')),
                ('comments', models.CharField(default='None', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('conservation_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boranga.conservationlist')),
                ('conservation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationcategory')),
                ('conservation_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationcriteria')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('department_file_numbers', models.CharField(default='None', max_length=512)),
                ('community_original_area', models.IntegerField(default=-1)),
                ('community_original_area_accuracy', models.IntegerField(default=-1)),
                ('number_of_occurrences', models.IntegerField(default=-1)),
                ('extent_of_occurrences', models.IntegerField(default=-1)),
                ('area_of_occupancy', models.IntegerField(default=-1)),
                ('number_of_iucn_locations', models.IntegerField(default=-1)),
                ('community_original_area_reference', models.CharField(default='None', max_length=512)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boranga.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField(default=-1)),
                ('category_id', models.IntegerField(default=-1)),
                ('status', models.CharField(default='None', max_length=512)),
                ('document', models.CharField(default='None', max_length=512)),
                ('document_description', models.CharField(default='None', max_length=1024)),
                ('date_time', models.DateField()),
                ('species', models.ManyToManyField(to='boranga.Species')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='taxonomy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boranga.taxonomy'),
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=128)),
                ('species_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.speciesdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_category_id', models.IntegerField(default=-1)),
                ('threat_description', models.CharField(default='None', max_length=512)),
                ('comment', models.CharField(default='None', max_length=512)),
                ('document', models.CharField(default='None', max_length=1024)),
                ('source', models.CharField(default='None', max_length=1024)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.species')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_category_id', models.IntegerField(default=-1)),
                ('region_id', models.IntegerField(default=-1)),
                ('district_id', models.IntegerField(default=-1)),
                ('type', models.CharField(default='None', max_length=512)),
                ('comment', models.CharField(default='None', max_length=512)),
                ('source', models.CharField(default='None', max_length=1024)),
                ('species', models.ManyToManyField(to='boranga.Species')),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='conservation_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationstatus'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(default='None', max_length=128)),
                ('community_id', models.IntegerField(default=-1)),
                ('community_status', models.CharField(default='None', max_length=128)),
                ('region', models.IntegerField(default=-1)),
                ('district', models.IntegerField(default=-1)),
                ('species', models.ManyToManyField(to='boranga.Species')),
                ('conservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationstatus')),
            ],
        ),
    ]
