# Generated by Django 3.2.4 on 2022-02-01 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0003_auto_20220119_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='conservation_status',
        ),
        migrations.AddField(
            model_name='grouptype',
            name='group_type_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.CharField(choices=[('flora', 'Flora'), ('fauna', 'Fauna'), ('community', 'Community')], default=('fauna', 'Fauna'), max_length=128),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='date_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxon_id',
            field=models.IntegerField(default=-1),
        ),
    ]
