# Generated by Django 3.2.12 on 2022-05-26 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0003_auto_20220512_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_file_numbers', models.CharField(blank=True, default='None', max_length=512, null=True)),
                ('number_of_occurrences', models.IntegerField(default=-1, null=True)),
                ('extent_of_occurrences', models.IntegerField(default=-1, null=True)),
                ('area_of_occupancy', models.IntegerField(default=-1, null=True)),
                ('number_of_iucn_locations', models.IntegerField(default=-1, null=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_distribution', to='boranga.species', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_original_area', models.IntegerField(default=-1, null=True)),
                ('community_original_area_accuracy', models.IntegerField(default=-1, null=True)),
                ('community_original_area_reference', models.CharField(default='None', max_length=512, null=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_distribution', to='boranga.community', unique=True)),
            ],
        ),
    ]
