# Generated by Django 3.2.12 on 2022-05-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0004_communitydistribution_speciesdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_description',
            field=models.CharField(default='None', max_length=2048),
        ),
    ]
