# Generated by Django 3.2.12 on 2022-05-31 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0005_community_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_description',
            field=models.CharField(blank=True, default='None', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(blank=True, default='None', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_status',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='conservation_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationstatus'),
        ),
        migrations.AlterField(
            model_name='community',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.region'),
        ),
        migrations.AlterField(
            model_name='community',
            name='species',
            field=models.ManyToManyField(blank=True, null=True, to='boranga.Species'),
        ),
        migrations.AlterField(
            model_name='communitydistribution',
            name='community_original_area',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='communitydistribution',
            name='community_original_area_accuracy',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='communitydistribution',
            name='community_original_area_reference',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='biological_attributes',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='comments',
            field=models.CharField(blank=True, default='None', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='ecological_attributes',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='general_management_advice',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='specific_survey_advice',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='conservation_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationstatus'),
        ),
        migrations.AlterField(
            model_name='species',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.district'),
        ),
        migrations.AlterField(
            model_name='species',
            name='image',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='name_currency',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='processing_status',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.region'),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, default='None', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxonomy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.taxonomy'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='family',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='genus',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.nameauthority'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='phylogenetic_group',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='previous_name',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxon',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxon_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
