# Generated by Django 3.2.12 on 2022-06-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0007_alter_community_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='last_data_curration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='last_data_curration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
