# Generated by Django 3.2.12 on 2022-06-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0008_auto_20220602_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesdocument',
            options={'verbose_name': 'Species Document'},
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='document_category_name',
            field=models.CharField(default='None', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.documentcategory'),
        ),
        migrations.CreateModel(
            name='DocumentSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_sub_category_name', models.CharField(max_length=128, unique=True)),
                ('document_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sub_category', to='boranga.documentcategory')),
            ],
        ),
        migrations.AddField(
            model_name='speciesdocument',
            name='document_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.documentsubcategory'),
        ),
    ]
