# Generated by Django 3.2.12 on 2022-06-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0009_auto_20220608_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubcategory',
            name='document_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sub_categories', to='boranga.documentcategory'),
        ),
    ]
