# Generated by Django 3.2.12 on 2022-06-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0011_alter_documentcategory_document_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubcategory',
            name='document_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.documentcategory'),
        ),
    ]
