# Generated by Django 3.2.12 on 2022-06-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0012_alter_documentsubcategory_document_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesdocument',
            old_name='document_sub_category',
            new_name='sub_category',
        ),
    ]
