# Generated by Django 3.2.12 on 2022-06-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0013_rename_document_sub_category_speciesdocument_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesdocument',
            old_name='sub_category',
            new_name='document_sub_category',
        ),
        migrations.AlterField(
            model_name='documentsubcategory',
            name='document_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sub_categories', to='boranga.documentcategory'),
        ),
    ]
