# Generated by Django 3.2.12 on 2022-06-09 06:27

import boranga.components.species_and_communities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0014_auto_20220608_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(default='None', max_length=512, upload_to=boranga.components.species_and_communities.models.update_species_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('community', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='community_documents', to='boranga.community')),
                ('document_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.documentcategory')),
                ('document_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.documentsubcategory')),
            ],
            options={
                'verbose_name': 'Community Document',
            },
        ),
    ]
