# Generated by Django 3.2.12 on 2022-06-10 05:44

import boranga.components.species_and_communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0015_communitydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydocument',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='speciesdocument',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='_file',
            field=models.FileField(default='None', max_length=512, upload_to=boranga.components.species_and_communities.models.update_community_doc_filename),
        ),
    ]
