# Generated by Django 3.2.12 on 2022-06-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0016_auto_20220610_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='species',
            name='species_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
