# Generated by Django 3.2.12 on 2022-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0019_conservationthreat_threat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationthreat',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
