# Generated by Django 3.2.12 on 2022-06-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0019_alter_conservationattributes_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationAttributesTemp',
            fields=[
                ('general_management_advice', models.CharField(blank=True, default='None', max_length=512, null=True)),
                ('ecological_attributes', models.CharField(blank=True, default='None', max_length=512, null=True)),
                ('biological_attributes', models.CharField(blank=True, default='None', max_length=512, null=True)),
                ('specific_survey_advice', models.CharField(blank=True, default='None', max_length=512, null=True)),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='species_conservation_attributes', serialize=False, to='boranga.species')),
                ('comments', models.CharField(blank=True, default='None', max_length=2048, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='species',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='boranga.species'),
        ),
    ]
