# Generated by Django 3.2.12 on 2022-06-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0020_auto_20220622_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConservationAttributes',
        ),
    ]
