# Generated by Django 3.2.12 on 2022-06-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0022_auto_20220622_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConservationAttributesTemp',
        ),
    ]
