# Generated by Django 3.2.12 on 2022-06-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0020_conservationthreat_visible'),
        ('boranga', '0023_delete_conservationattributestemp'),
    ]

    operations = [
    ]
