# Generated by Django 3.2.12 on 2022-06-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0024_merge_20220624_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='taxonomy',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_taxonomy', to='boranga.species', unique=True),
        ),
    ]
