# Generated by Django 3.2.12 on 2022-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0027_alter_taxonomy_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='community_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
