# Generated by Django 3.2.12 on 2022-07-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0028_auto_20220629_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='BConservationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', max_length=64)),
                ('label', models.CharField(default='None', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BConservationChangeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BConservationCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BConservationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', max_length=64)),
                ('label', models.CharField(default='None', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BConservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='None', max_length=512)),
                ('change_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.bconservationchangecode')),
                ('conservation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.bconservationcategory')),
                ('conservation_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.bconservationcriteria')),
                ('conservation_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.bconservationlist')),
            ],
        ),
    ]
