# Generated by Django 3.2.12 on 2022-07-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0032_auto_20220707_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('conservation_status_number', models.CharField(blank=True, default='', max_length=9)),
                ('change_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.conservationchangecode')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.community')),
                ('conservation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.conservationcategory')),
                ('conservation_criteria', models.ManyToManyField(blank=True, null=True, to='boranga.ConservationCriteria')),
                ('conservation_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationlist')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesConservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('conservation_status_number', models.CharField(blank=True, default='', max_length=9)),
                ('change_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.conservationchangecode')),
                ('conservation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.conservationcategory')),
                ('conservation_criteria', models.ManyToManyField(blank=True, null=True, to='boranga.ConservationCriteria')),
                ('conservation_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationlist')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.species')),
            ],
        ),
        migrations.DeleteModel(
            name='ConservationStatus',
        ),
    ]
