# Generated by Django 3.2.12 on 2022-07-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0033_auto_20220708_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationcategory',
            name='conservation_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conservation_categories', to='boranga.conservationlist'),
        ),
        migrations.AddField(
            model_name='conservationchangecode',
            name='label',
            field=models.CharField(default='None', max_length=512),
        ),
        migrations.AddField(
            model_name='conservationcriteria',
            name='conservation_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conservation_criterias', to='boranga.conservationlist'),
        ),
        migrations.AddField(
            model_name='conservationcriteria',
            name='label',
            field=models.CharField(default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='communityconservationstatus',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_status', to='boranga.community'),
        ),
        migrations.AlterField(
            model_name='conservationcategory',
            name='label',
            field=models.CharField(default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='conservationlist',
            name='label',
            field=models.CharField(default='None', max_length=512),
        ),
        migrations.AlterField(
            model_name='speciesconservationstatus',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_status', to='boranga.species'),
        ),
    ]
