# Generated by Django 3.2.12 on 2022-07-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0034_auto_20220708_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationlist',
            name='is_commonwealth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conservationlist',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conservationlist',
            name='is_wa',
            field=models.BooleanField(default=False),
        ),
    ]
