# Generated by Django 3.2.12 on 2022-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0035_auto_20220713_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conservationlist',
            old_name='is_commonwealth',
            new_name='applies_to_commonwealth',
        ),
        migrations.RenameField(
            model_name='conservationlist',
            old_name='is_international',
            new_name='applies_to_international',
        ),
        migrations.RenameField(
            model_name='conservationlist',
            old_name='is_wa',
            new_name='applies_to_wa',
        ),
        migrations.AddField(
            model_name='conservationlist',
            name='applies_to_communities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conservationlist',
            name='applies_to_species',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conservationlist',
            name='approval_level',
            field=models.CharField(choices=[('intermediate', 'Intermediate'), ('minister', 'Minister')], default='intermediate', max_length=20, verbose_name='Approval level'),
        ),
    ]
