# Generated by Django 3.2.12 on 2022-07-21 09:21

import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0036_auto_20220714_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitydocument",
            name="_file",
            field=models.FileField(
                default="None",
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga4/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_community_doc_filename,
            ),
        ),
        migrations.AlterField(
            model_name="communitylogdocument",
            name="_file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga4/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_community_comms_log_filename,
            ),
        ),
        migrations.AlterField(
            model_name="speciesdocument",
            name="_file",
            field=models.FileField(
                default="None",
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga4/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_species_doc_filename,
            ),
        ),
        migrations.AlterField(
            model_name="specieslogdocument",
            name="_file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/data/data/projects/boranga4/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_species_comms_log_filename,
            ),
        ),
    ]
