# Generated by Django 3.2.12 on 2022-08-01 08:08

import boranga.components.organisations.models
import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0037_auto_20220721_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhylogeneticGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="communitydocument",
            name="_file",
            field=models.FileField(
                default="None",
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_community_doc_filename,
            ),
        ),
        migrations.AlterField(
            model_name="communitylogdocument",
            name="_file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_community_comms_log_filename,
            ),
        ),
        migrations.AlterField(
            model_name="organisationlogdocument",
            name="_file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to=boranga.components.organisations.models.update_organisation_comms_log_filename,
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequest",
            name="identification",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to="organisation/requests/%Y/%m/%d",
            ),
        ),
        migrations.AlterField(
            model_name="organisationrequestlogdocument",
            name="_file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to=boranga.components.organisations.models.update_organisation_request_comms_log_filename,
            ),
        ),
        migrations.AlterField(
            model_name="speciesdocument",
            name="_file",
            field=models.FileField(
                default="None",
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_species_doc_filename,
            ),
        ),
        migrations.AlterField(
            model_name="specieslogdocument",
            name="_file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/priya/projects/boranga/private-media/",
                ),
                upload_to=boranga.components.species_and_communities.models.update_species_comms_log_filename,
            ),
        ),
    ]
