# Generated by Django 3.2.12 on 2022-08-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0038_auto_20220801_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='family',
        ),
    ]
