# Generated by Django 3.2.12 on 2022-08-03 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0039_remove_taxonomy_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.family'),
        ),
    ]
