# Generated by Django 3.2.12 on 2022-08-03 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0040_taxonomy_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='genus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.genus'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='phylogenetic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.phylogeneticgroup'),
        ),
    ]
