# Generated by Django 3.2.12 on 2022-08-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0041_auto_20220803_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='name_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.nameauthority'),
        ),
        migrations.AddField(
            model_name='community',
            name='name_comments',
            field=models.CharField(blank=True, default='None', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='previous_name',
            field=models.CharField(blank=True, default='None', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name_comments',
            field=models.CharField(blank=True, default='None', max_length=2048, null=True),
        ),
    ]
