# Generated by Django 3.2.12 on 2022-08-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0043_breedingperiod_faunabreeding_florarecruitmenttype_floweringperiod_fruitingperiod_pollinatorinformati'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesConservationAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydrology', models.CharField(blank=True, max_length=200, null=True)),
                ('response_to_dieback', models.CharField(blank=True, max_length=500, null=True)),
                ('fauna_reproductive_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('diet_and_food_source', models.CharField(blank=True, max_length=200, null=True)),
                ('home_range', models.CharField(blank=True, max_length=200, null=True)),
                ('habitat_growth_form', models.CharField(blank=True, max_length=200, null=True)),
                ('time_to_maturity', models.IntegerField(blank=True, default=0, null=True)),
                ('generation_length', models.IntegerField(blank=True, default=0, null=True)),
                ('average_lifespan', models.IntegerField(blank=True, default=0, null=True)),
                ('minimum_fire_interval', models.CharField(blank=True, max_length=200, null=True)),
                ('response_to_fire', models.CharField(blank=True, max_length=200, null=True)),
                ('response_to_dsturbance', models.CharField(blank=True, max_length=500, null=True)),
                ('habitat', models.CharField(blank=True, max_length=200, null=True)),
                ('research_requirements', models.CharField(blank=True, max_length=500, null=True)),
                ('other_relevant_diseases', models.CharField(blank=True, max_length=500, null=True)),
                ('breeding_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.breedingperiod')),
                ('fauna_breeding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.faunabreeding')),
                ('flora_recruitment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.florarecruitmenttype')),
                ('flowering_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.floweringperiod')),
                ('fruiting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.fruitingperiod')),
                ('pollinator_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.pollinatorinformation')),
                ('post_fire_habitat_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.postfirehabitatinteraction')),
                ('root_morphology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.rootmorphology')),
                ('seed_viability_germination_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.seedviabilitygerminationinfo')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_conservation_attributes', to='boranga.species', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='conservationattributes',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conservation_attributes', to='boranga.species', unique=True),
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
    ]
