# Generated by Django 3.2.12 on 2022-08-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0044_auto_20220805_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConservationAttributes',
        ),
    ]
