# Generated by Django 3.2.12 on 2022-08-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0045_delete_conservationattributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesconservationattributes',
            old_name='response_to_dsturbance',
            new_name='response_to_disturbance',
        ),
    ]
