# Generated by Django 3.2.12 on 2022-08-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0046_rename_response_to_dsturbance_speciesconservationattributes_response_to_disturbance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConservationAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat_growth_form', models.CharField(blank=True, max_length=200, null=True)),
                ('minimum_fire_interval', models.CharField(blank=True, max_length=200, null=True)),
                ('response_to_fire', models.CharField(blank=True, max_length=200, null=True)),
                ('hydrology', models.CharField(blank=True, max_length=200, null=True)),
                ('ecological_and_biological_information', models.CharField(blank=True, max_length=500, null=True)),
                ('research_requirements', models.CharField(blank=True, max_length=500, null=True)),
                ('response_to_dieback', models.CharField(blank=True, max_length=500, null=True)),
                ('other_relevant_diseases', models.CharField(blank=True, max_length=500, null=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_conservation_attributes', to='boranga.community', unique=True)),
                ('pollinator_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.pollinatorinformation')),
                ('post_fire_habitat_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.postfirehabitatinteraction')),
            ],
        ),
    ]
