# Generated by Django 3.2.12 on 2022-08-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0048_rename_community_id_community_community_migrated_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='previous_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='previous_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
