# Generated by Django 3.2.12 on 2022-08-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0050_auto_20220810_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
