# Generated by Django 3.2.12 on 2022-08-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0051_scientificname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='scientific_name',
        ),
    ]
