# Generated by Django 3.2.12 on 2022-08-11 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0052_remove_species_scientific_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.scientificname'),
        ),
    ]
