# Generated by Django 3.2.12 on 2022-08-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0053_species_scientific_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
