# Generated by Django 3.2.12 on 2022-08-11 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0054_communityname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_name',
        ),
    ]
