# Generated by Django 3.2.12 on 2022-08-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0056_community_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydistribution',
            name='area_of_occupancy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='area_of_occupancy_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='department_file_numbers',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='extent_of_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='number_of_iucn_locations',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='number_of_occurrences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesdistribution',
            name='area_of_occupancy_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
