# Generated by Django 3.2.12 on 2022-08-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0057_auto_20220812_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitydistribution',
            name='aoo_actual_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='aoo_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='eoo_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='noo_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciesdistribution',
            name='aoo_actual_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciesdistribution',
            name='aoo_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciesdistribution',
            name='eoo_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speciesdistribution',
            name='noo_auto',
            field=models.BooleanField(default=True),
        ),
    ]
