# Generated by Django 3.2.12 on 2022-08-17 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0058_auto_20220812_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conservationcategory',
            options={'verbose_name': 'Conservation Category', 'verbose_name_plural': 'Conservation Categories'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Document Category', 'verbose_name_plural': 'Document Categories'},
        ),
        migrations.AlterModelOptions(
            name='documentsubcategory',
            options={'verbose_name': 'Document Sub Category', 'verbose_name_plural': 'Document Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='nameauthority',
            options={'verbose_name': 'Name Authority', 'verbose_name_plural': 'Name Authorities'},
        ),
        migrations.AlterModelOptions(
            name='rootmorphology',
            options={'verbose_name': 'Root Morphology', 'verbose_name_plural': 'Root Morphologies'},
        ),
        migrations.AlterModelOptions(
            name='threatcategory',
            options={'verbose_name': 'Threat Category', 'verbose_name_plural': 'Threat Categories'},
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='proposed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='recurrence_pattern',
            field=models.SmallIntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='recurrence_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='proposed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='recurrence_pattern',
            field=models.SmallIntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='recurrence_schedule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
