# Generated by Django 3.2.12 on 2022-08-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0059_auto_20220817_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityconservationstatus',
            old_name='proposed',
            new_name='proposed_date',
        ),
        migrations.RenameField(
            model_name='speciesconservationstatus',
            old_name='proposed',
            new_name='proposed_date',
        ),
    ]
