# Generated by Django 3.2.12 on 2022-08-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0060_auto_20220817_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityconservationstatus',
            old_name='conservation_category',
            new_name='current_conservation_category',
        ),
        migrations.RenameField(
            model_name='communityconservationstatus',
            old_name='conservation_criteria',
            new_name='current_conservation_criteria',
        ),
        migrations.RenameField(
            model_name='communityconservationstatus',
            old_name='conservation_list',
            new_name='current_conservation_list',
        ),
        migrations.RenameField(
            model_name='speciesconservationstatus',
            old_name='conservation_category',
            new_name='current_conservation_category',
        ),
        migrations.RenameField(
            model_name='speciesconservationstatus',
            old_name='conservation_criteria',
            new_name='current_conservation_criteria',
        ),
        migrations.RenameField(
            model_name='speciesconservationstatus',
            old_name='conservation_list',
            new_name='current_conservation_list',
        ),
    ]
