# Generated by Django 3.2.12 on 2022-08-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0063_auto_20220825_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='curr_conservation_criteria',
        ),
    ]
