# Generated by Django 3.2.12 on 2022-08-26 05:03

import boranga.components.conservation_status.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0064_remove_speciesconservationstatus_curr_conservation_criteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesConservationStatusLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boranga.communicationslogentry')),
                ('species_conservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='boranga.speciesconservationstatus')),
            ],
            bases=('boranga.communicationslogentry',),
        ),
        migrations.CreateModel(
            name='SpeciesConservationStatusLogDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/home/priya/projects/boranga/private-media/'), upload_to=boranga.components.conservation_status.models.update_species_conservation_status_comms_log_filename)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='boranga.speciesconservationstatuslogentry')),
            ],
        ),
    ]
