# Generated by Django 3.2.12 on 2022-08-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0066_auto_20220826_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityconservationstatus',
            name='lodgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='lodgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
