# Generated by Django 3.2.12 on 2022-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0068_speciesconservationstatususeraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityconservationstatus',
            name='approved_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='assigned_approver',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='assigned_officer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='with_assessor', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='prev_processing_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='with_assessor', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='communityconservationstatus',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status'),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='approved_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='assigned_approver',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='assigned_officer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='with_assessor', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='prev_processing_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='with_assessor', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='speciesconservationstatus',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status'),
        ),
    ]
