# Generated by Django 3.2.12 on 2022-09-01 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0069_auto_20220830_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='with_assessor', max_length=40, verbose_name='Customer Status')),
                ('conservation_status_number', models.CharField(blank=True, default='', max_length=9)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('recurrence_pattern', models.SmallIntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1)),
                ('recurrence_schedule', models.IntegerField(blank=True, null=True)),
                ('proposed_date', models.DateTimeField(auto_now_add=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('submitter', models.IntegerField(null=True)),
                ('lodgement_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.IntegerField(null=True)),
                ('assigned_approver', models.IntegerField(null=True)),
                ('approved_by', models.IntegerField(null=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='with_assessor', max_length=30, verbose_name='Processing Status')),
                ('prev_processing_status', models.CharField(blank=True, max_length=30, null=True)),
                ('review_status', models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status')),
                ('change_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.conservationchangecode')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_status', to='boranga.community')),
                ('current_conservation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curr_conservation_category', to='boranga.conservationcategory')),
                ('current_conservation_criteria', models.ManyToManyField(blank=True, null=True, related_name='curr_conservation_criteria', to='boranga.ConservationCriteria')),
                ('current_conservation_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curr_conservation_list', to='boranga.conservationlist')),
                ('proposed_conservation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prop_conservation_category', to='boranga.conservationcategory')),
                ('proposed_conservation_criteria', models.ManyToManyField(blank=True, null=True, related_name='prop_conservation_criteria', to='boranga.ConservationCriteria')),
                ('proposed_conservation_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prop_conservation_list', to='boranga.conservationlist')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_status', to='boranga.species')),
            ],
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='change_code',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='current_conservation_category',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='current_conservation_criteria',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='current_conservation_list',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='proposed_conservation_category',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='proposed_conservation_criteria',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='proposed_conservation_list',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatus',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatuslogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatuslogentry',
            name='communicationslogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatuslogentry',
            name='species_conservation_status',
        ),
        migrations.RemoveField(
            model_name='speciesconservationstatususeraction',
            name='species_conservation_status',
        ),
        migrations.DeleteModel(
            name='CommunityConservationStatus',
        ),
        migrations.DeleteModel(
            name='SpeciesConservationStatus',
        ),
        migrations.DeleteModel(
            name='SpeciesConservationStatusLogDocument',
        ),
        migrations.DeleteModel(
            name='SpeciesConservationStatusLogEntry',
        ),
        migrations.DeleteModel(
            name='SpeciesConservationStatusUserAction',
        ),
    ]
