# Generated by Django 3.2.15 on 2022-09-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0073_auto_20220906_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.grouptype'),
        ),
    ]
