# Generated by Django 3.2.15 on 2022-09-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0074_conservationstatus_application_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conservationstatus',
            old_name='current_conservation_category',
            new_name='conservation_category',
        ),
        migrations.RenameField(
            model_name='conservationstatus',
            old_name='current_conservation_criteria',
            new_name='conservation_criteria',
        ),
        migrations.RenameField(
            model_name='conservationstatus',
            old_name='current_conservation_list',
            new_name='conservation_list',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='proposed_conservation_category',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='proposed_conservation_criteria',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='proposed_conservation_list',
        ),
    ]
