# Generated by Django 3.2.15 on 2022-09-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0075_auto_20220914_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='customer',
            field=models.IntegerField(null=True),
        ),
    ]
