# Generated by Django 3.2.15 on 2022-10-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0078_conservationstatusamendmentrequest_conservationstatusamendmentrequestdocument_conservationstatusprop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationstatusproposalrequest',
            name='officer',
            field=models.IntegerField(null=True),
        ),
    ]
