# Generated by Django 3.2.15 on 2022-10-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0079_alter_conservationstatusproposalrequest_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='assessor_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='deficiency_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatusreferral',
            name='referral_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
