# Generated by Django 3.2.16 on 2022-11-22 07:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0083_conservationstatus_proposed_decline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='proposal_type',
            field=models.CharField(choices=[('new_proposal', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('external', 'External')], default='new_proposal', max_length=40, verbose_name='Application Status Type'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='proposed_issuance_approval',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
