# Generated by Django 3.2.16 on 2022-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0084_auto_20221122_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='approver_comment',
            field=models.TextField(blank=True),
        ),
    ]
