# Generated by Django 3.2.16 on 2022-11-24 06:42

import boranga.components.conservation_status.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0085_conservationstatus_approver_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationStatusDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.conservation_status.models.update_conservation_status_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('conservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='boranga.conservationstatus')),
            ],
            options={
                'verbose_name': 'Conservation Status Document',
            },
        ),
        migrations.CreateModel(
            name='ConservationStatusIssuanceApprovalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer', models.IntegerField()),
                ('effective_from_date', models.DateTimeField(blank=True, null=True)),
                ('effective_to_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('conservation_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationstatus')),
                ('conservation_status_approval_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conservation_status_approval_document', to='boranga.conservationstatusdocument')),
            ],
        ),
    ]
