# Generated by Django 3.2.16 on 2022-11-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0086_conservationstatusdocument_conservationstatusissuanceapprovaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatusissuanceapprovaldetails',
            name='cc_email',
            field=models.TextField(null=True),
        ),
    ]
