# Generated by Django 3.2.16 on 2022-12-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0088_auto_20221201_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationstatus',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
