# Generated by Django 3.2.16 on 2022-12-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0089_auto_20221206_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatusdocument',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentcategory'),
        ),
        migrations.AddField(
            model_name='conservationstatusdocument',
            name='document_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentsubcategory'),
        ),
        migrations.AddField(
            model_name='conservationstatusdocument',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentcategory'),
        ),
        migrations.AlterField(
            model_name='communitydocument',
            name='document_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentsubcategory'),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='document_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentcategory'),
        ),
        migrations.AlterField(
            model_name='speciesdocument',
            name='document_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentsubcategory'),
        ),
    ]
