# Generated by Django 3.2.16 on 2022-12-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0090_auto_20221208_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatusdocument',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
