# Generated by Django 3.2.16 on 2022-12-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0091_conservationstatusdocument_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='internal_application',
            field=models.BooleanField(default=False),
        ),
    ]
