# Generated by Django 3.2.16 on 2023-01-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0092_conservationstatus_internal_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vernacular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vernacular_id', models.IntegerField(blank=True, null=True)),
                ('vernacular_name', models.CharField(blank=True, max_length=512, null=True)),
                ('taxon_name_id', models.IntegerField(blank=True, null=True)),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxon_vernacular', to='boranga.taxonomy', unique=True)),
            ],
        ),
    ]
