# Generated by Django 3.2.16 on 2023-01-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0093_vernacular'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonVernacular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vernacular_id', models.IntegerField(blank=True, null=True)),
                ('vernacular_name', models.CharField(blank=True, max_length=512, null=True)),
                ('taxon_name_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='taxonomy',
            old_name='taxon_id',
            new_name='taxon_name_id',
        ),
        migrations.RemoveField(
            model_name='species',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='name_currency',
        ),
        migrations.RemoveField(
            model_name='species',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='species',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='taxon',
        ),
        migrations.AddField(
            model_name='species',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.taxonomy'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name_currency',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='Vernacular',
        ),
        migrations.AddField(
            model_name='taxonvernacular',
            name='taxonomy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vernaculars', to='boranga.taxonomy', unique=True),
        ),
    ]
