# Generated by Django 3.2.16 on 2023-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0094_auto_20230111_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='lodgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='submitter',
            field=models.IntegerField(null=True),
        ),
    ]
