# Generated by Django 3.2.16 on 2023-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0095_auto_20230113_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='lodgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='submitter',
            field=models.IntegerField(null=True),
        ),
    ]
