# Generated by Django 3.2.16 on 2023-01-19 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0098_speciesuseraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image_doc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_image', to='boranga.communitydocument'),
        ),
        migrations.AddField(
            model_name='species',
            name='image_doc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_image', to='boranga.speciesdocument'),
        ),
    ]
