# Generated by Django 3.2.16 on 2023-01-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0095_alter_taxonvernacular_taxonomy'),
        ('boranga', '0099_auto_20230119_1150'),
    ]

    operations = [
    ]
