# Generated by Django 3.2.16 on 2023-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0101_auto_20230127_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='approved_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='approver_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='assessor_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='assigned_approver',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='assigned_officer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AddField(
            model_name='community',
            name='deficiency_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='prev_processing_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AddField(
            model_name='community',
            name='proposal_type',
            field=models.CharField(choices=[('new_proposal', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('external', 'External')], default='new_proposal', max_length=40, verbose_name='Application Status Type'),
        ),
        migrations.AddField(
            model_name='community',
            name='proposed_decline_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status'),
        ),
    ]
