# Generated by Django 3.2.16 on 2023-01-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0102_auto_20230131_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('awaiting_amendments', 'Awaiting Amendments'), ('amended', 'Amended'), ('accepted', 'Accepted')], default='not_reviewed', max_length=30, verbose_name='Review Status'),
        ),
    ]
