# Generated by Django 3.2.16 on 2023-02-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0103_species_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='species',
            name='approver_comment',
        ),
        migrations.RemoveField(
            model_name='species',
            name='assessor_data',
        ),
        migrations.RemoveField(
            model_name='species',
            name='assigned_approver',
        ),
        migrations.RemoveField(
            model_name='species',
            name='assigned_officer',
        ),
        migrations.RemoveField(
            model_name='species',
            name='customer_status',
        ),
        migrations.RemoveField(
            model_name='species',
            name='deficiency_data',
        ),
        migrations.RemoveField(
            model_name='species',
            name='proposal_type',
        ),
        migrations.RemoveField(
            model_name='species',
            name='proposed_decline_status',
        ),
        migrations.RemoveField(
            model_name='species',
            name='review_status',
        ),
        migrations.AlterField(
            model_name='species',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('current', 'Current'), ('historical', 'Historical'), ('historical', 'Historical'), ('to_be_split', 'To Be Split'), ('to_be_combined', 'To Be Combined'), ('to_be_renamed', 'To Be Renamed')], default='draft', max_length=30, null=True, verbose_name='Processing Status'),
        ),
    ]
