# Generated by Django 3.2.16 on 2023-02-07 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0104_auto_20230202_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='community',
            name='approver_comment',
        ),
        migrations.RemoveField(
            model_name='community',
            name='assessor_data',
        ),
        migrations.RemoveField(
            model_name='community',
            name='assigned_approver',
        ),
        migrations.RemoveField(
            model_name='community',
            name='assigned_officer',
        ),
        migrations.RemoveField(
            model_name='community',
            name='customer_status',
        ),
        migrations.RemoveField(
            model_name='community',
            name='deficiency_data',
        ),
        migrations.RemoveField(
            model_name='community',
            name='proposal_type',
        ),
        migrations.RemoveField(
            model_name='community',
            name='proposed_decline_status',
        ),
        migrations.RemoveField(
            model_name='community',
            name='review_status',
        ),
        migrations.AddField(
            model_name='community',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.taxonomy', unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('historical', 'Historical'), ('to_be_split', 'To Be Split'), ('to_be_combined', 'To Be Combined'), ('to_be_renamed', 'To Be Renamed')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='species',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('current', 'Current'), ('historical', 'Historical'), ('to_be_split', 'To Be Split'), ('to_be_combined', 'To Be Combined'), ('to_be_renamed', 'To Be Renamed')], default='draft', max_length=30, null=True, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='species',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.taxonomy', unique=True),
        ),
    ]
