# Generated by Django 3.2.16 on 2023-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0105_auto_20230207_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='community_description',
        ),
        migrations.RemoveField(
            model_name='community',
            name='community_migrated_id',
        ),
        migrations.RemoveField(
            model_name='community',
            name='community_name',
        ),
        migrations.RemoveField(
            model_name='community',
            name='community_status',
        ),
        migrations.RemoveField(
            model_name='community',
            name='name_authority',
        ),
        migrations.RemoveField(
            model_name='community',
            name='name_comments',
        ),
        migrations.RemoveField(
            model_name='community',
            name='previous_name',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='community_description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='community_migrated_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='community_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='community_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
