# Generated by Django 3.2.16 on 2023-02-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0106_auto_20230207_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='community_description',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='community_migrated_id',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='community_name',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='community_status',
        ),
        migrations.CreateModel(
            name='CommunityTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_migrated_id', models.CharField(blank=True, max_length=200, null=True)),
                ('community_name', models.CharField(blank=True, max_length=512, null=True)),
                ('community_status', models.CharField(blank=True, max_length=128, null=True)),
                ('community_description', models.CharField(blank=True, max_length=2048, null=True)),
                ('name_currency', models.CharField(blank=True, max_length=16, null=True)),
                ('previous_name', models.CharField(blank=True, max_length=512, null=True)),
                ('name_comments', models.CharField(blank=True, max_length=500, null=True)),
                ('name_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.nameauthority')),
            ],
        ),
    ]
