# Generated by Django 3.2.16 on 2023-02-07 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0107_auto_20230207_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.communitytaxonomy', unique=True),
        ),
    ]
