# Generated by Django 3.2.16 on 2023-02-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0109_kingdom'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='kingdom_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
