# Generated by Django 3.2.16 on 2023-02-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0110_taxonomy_kingdom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kingdom',
            name='kingdom_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
