# Generated by Django 3.2.16 on 2023-02-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0111_kingdom_kingdom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='kingdom_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
