# Generated by Django 3.2.16 on 2023-02-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0113_alter_taxonomy_name_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_reference_id', models.IntegerField(blank=True, null=True)),
                ('cross_reference_type', models.CharField(blank=True, max_length=512, null=True)),
                ('old_name_id', models.IntegerField(blank=True, null=True)),
                ('new_name_id', models.IntegerField(blank=True, null=True)),
                ('new_taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_taxon', to='boranga.taxonomy')),
                ('old_taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_taxon', to='boranga.taxonomy')),
            ],
        ),
    ]
