# Generated by Django 3.2.16 on 2023-02-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0114_crossreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='parent_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='boranga.species'),
        ),
    ]
