# Generated by Django 3.2.16 on 2023-03-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0115_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('meeting', 'meeting'), ('committee_meeting', 'Committee Meeting')], default='meeting', max_length=30, verbose_name='Meeting Type'),
        ),
    ]
