# Generated by Django 3.2.16 on 2023-04-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0116_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
