# Generated by Django 3.2.16 on 2023-03-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0116_auto_20230315_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='family_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxon_family', to='boranga.taxonomy'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='family_nid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='taxon_rank_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='taxonomy_rank_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxons', to='boranga.taxonomyrank'),
        ),
    ]
