# Generated by Django 3.2.16 on 2023-03-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0117_auto_20230315_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_name_id', models.IntegerField(blank=True, null=True)),
                ('informal_group_id', models.IntegerField(blank=True, null=True)),
                ('informal_group_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phylo_group', to='boranga.taxonomy')),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informal_groups', to='boranga.taxonomy')),
            ],
        ),
    ]
