# Generated by Django 3.2.16 on 2023-03-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0118_informalgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_system_id', models.IntegerField(blank=True, null=True)),
                ('class_type', models.CharField(blank=True, max_length=100, null=True)),
                ('class_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='informalgroup',
            name='informal_group_fk',
        ),
        migrations.AddField(
            model_name='informalgroup',
            name='classification_system_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informalgroup',
            name='classification_system_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informal_groups', to='boranga.classificationsystem'),
        ),
    ]
