# Generated by Django 3.2.16 on 2023-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0119_auto_20230316_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='_boranga_species_species_parent_+', to='boranga.Species'),
        ),
    ]
