# Generated by Django 3.2.16 on 2023-04-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0120_species_species_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='parent_species',
        ),
    ]
