# Generated by Django 3.2.16 on 2023-04-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0121_remove_species_parent_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='species_parent',
        ),
        migrations.AddField(
            model_name='species',
            name='parent_species',
            field=models.ManyToManyField(blank=True, null=True, related_name='_boranga_species_parent_species_+', to='boranga.Species'),
        ),
    ]
