# Generated by Django 3.2.16 on 2023-04-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0117_meeting_processing_status'),
        ('boranga', '0122_auto_20230405_1043'),
    ]

    operations = [
    ]
