# Generated by Django 3.2.16 on 2023-05-18 03:49

import boranga.components.meetings.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0123_merge_20230417_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_number',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('minutes_number', models.CharField(blank=True, default='', max_length=9)),
                ('_file', models.FileField(default='None', max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.meetings.models.update_meeting_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('document_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentcategory')),
                ('document_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentsubcategory')),
                ('meeting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='boranga.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Minutes',
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='boranga.meetingroom'),
        ),
    ]
