# Generated by Django 3.2.16 on 2023-05-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0125_meetinglogdocument_meetinglogentry_meetinguseraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='lodgement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='submitter',
            field=models.IntegerField(null=True),
        ),
    ]
