# Generated by Django 3.2.16 on 2023-05-31 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0126_auto_20230524_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommiteeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=328, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendess',
            field=models.CharField(blank=True, max_length=1208, null=True),
        ),
        migrations.CreateModel(
            name='Commitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=328, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='commitee_members', to='boranga.CommiteeMembers')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='commitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee', to='boranga.commitee'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='selected_commitee_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='selected_commitee_members', to='boranga.CommiteeMembers'),
        ),
    ]
