# Generated by Django 3.2.16 on 2023-06-02 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0128_rename_attendess_meeting_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=328, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='commitee',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='selected_commitee_members',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('committee_meeting', 'Committee Meeting')], default='meeting', max_length=30, verbose_name='Meeting Type'),
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=328, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='committee_members', to='boranga.CommitteeMembers')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee', to='boranga.committee'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='selected_committee_members',
            field=models.ManyToManyField(blank=True, null=True, to='boranga.CommitteeMembers'),
        ),
    ]
