# Generated by Django 3.2.16 on 2023-06-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0129_auto_20230602_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commitee',
        ),
        migrations.DeleteModel(
            name='CommiteeMembers',
        ),
    ]
