# Generated by Django 3.2.16 on 2023-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0130_auto_20230602_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.ManyToManyField(blank=True, null=True, to='boranga.ConservationStatus'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('ready_for_agenda', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('ready_for_agenda', 'Ready For Agenda'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
