# Generated by Django 3.2.16 on 2023-06-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0131_auto_20230613_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('conservation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationstatus')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='boranga.meeting')),
            ],
        ),
    ]
