# Generated by Django 3.2.16 on 2023-06-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0133_alter_agendaitem_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConservationPlan',
        ),
    ]
