# Generated by Django 3.2.16 on 2023-06-19 06:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0134_delete_conservationplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConservationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('new_proposal', 'New Application'), ('amendment', 'Amendment'), ('renewal', 'Renewal'), ('external', 'External')], default='new_proposal', max_length=40, verbose_name='Application Status Type')),
                ('conservation_plan_number', models.CharField(blank=True, default='', max_length=9)),
                ('wa_plan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('recurrence_pattern', models.SmallIntegerField(choices=[(1, 'Month'), (2, 'Year')], default=1)),
                ('recurrence_schedule', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('submitter', models.IntegerField(null=True)),
                ('lodgement_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.IntegerField(null=True)),
                ('assigned_approver', models.IntegerField(null=True)),
                ('approved_by', models.IntegerField(null=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('ready_for_agenda', 'Ready For Agenda'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed'), ('current_waiting_replacement', 'Cuurent Waiting Replacement'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined')], default='draft', max_length=30, verbose_name='Processing Status')),
                ('prev_processing_status', models.CharField(blank=True, max_length=30, null=True)),
                ('proposed_decline_status', models.BooleanField(default=False)),
                ('deficiency_data', models.TextField(blank=True, null=True)),
                ('assessor_data', models.TextField(blank=True, null=True)),
                ('proposed_issuance_approval', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('approver_comment', models.TextField(blank=True)),
                ('application_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.grouptype')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.district')),
                ('old_conservation_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=150, null=True)),
                ('valid_months', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationPlanSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('conservation_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationplan')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.species')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationPlanCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.community')),
                ('conservation_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationplan')),
            ],
        ),
        migrations.AddField(
            model_name='conservationplan',
            name='plan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.plantype'),
        ),
        migrations.AddField(
            model_name='conservationplan',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.region'),
        ),
    ]
