# Generated by Django 3.2.16 on 2023-06-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0135_auto_20230619_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitem',
            options={'ordering': ['meeting', 'order']},
        ),
        migrations.RemoveField(
            model_name='committee',
            name='members',
        ),
        migrations.AddField(
            model_name='committeemembers',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.committee'),
        ),
        migrations.AddConstraint(
            model_name='agendaitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'order'), name='unique agenda order per Meeting'),
        ),
    ]
