# Generated by Django 3.2.16 on 2023-06-22 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0136_auto_20230622_1041'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendaitem',
            name='unique agenda order per Meeting',
        ),
    ]
