# Generated by Django 3.2.16 on 2023-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0137_remove_agendaitem_unique agenda order per meeting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agendaitem',
            constraint=models.UniqueConstraint(fields=('meeting', 'order'), name='unique agenda order per Meeting'),
        ),
    ]
