# Generated by Django 3.2.16 on 2023-06-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0138_agendaitem_unique agenda order per meeting'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendaitem',
            name='unique agenda order per Meeting',
        ),
    ]
