# Generated by Django 3.2.16 on 2023-06-30 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0140_auto_20230630_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorposalAmendmentReason',
            new_name='ProposalAmendmentReason',
        ),
    ]
