# Generated by Django 3.2.20 on 2023-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0143_auto_20230711_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='comment',
            field=models.CharField(blank=True, default='test comment', max_length=500, null=True),
        ),
    ]
