# Generated by Django 3.2.20 on 2023-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0144_taxonomy_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='comment',
        ),
        migrations.AddField(
            model_name='species',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
