# Generated by Django 3.2.20 on 2023-07-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0148_auto_20230721_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('historical', 'Historical'), ('to_be_split', 'To Be Split'), ('to_be_combined', 'To Be Combined'), ('to_be_renamed', 'To Be Renamed')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='species',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('historical', 'Historical'), ('to_be_split', 'To Be Split'), ('to_be_combined', 'To Be Combined'), ('to_be_renamed', 'To Be Renamed')], default='draft', max_length=30, null=True, verbose_name='Processing Status'),
        ),
    ]
