# Generated by Django 3.2.20 on 2023-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0149_auto_20230721_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='flora_recruitment_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='diet_and_food_source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='fauna_breeding',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='fauna_reproductive_capacity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='habitat',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='home_range',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='other_relevant_diseases',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='pollinator_information',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='research_requirements',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='response_to_dieback',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='seed_viability_germination_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
