# Generated by Django 3.2.20 on 2023-07-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0151_auto_20230728_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytaxonomy',
            name='community_status',
        ),
        migrations.AlterField(
            model_name='communitytaxonomy',
            name='name_authority',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
