# Generated by Django 3.2.20 on 2023-08-02 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0152_auto_20230728_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='taxonomy',
        ),
        migrations.AddField(
            model_name='communitytaxonomy',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy', to='boranga.community', unique=True),
        ),
    ]
