# Generated by Django 3.2.20 on 2023-08-04 07:31

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0154_speciesconservationattributes_flowering_prd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='proposalamendmentreason',
            options={'verbose_name': 'Proposal Amendment Reason', 'verbose_name_plural': 'Proposal Amendment Reasons'},
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='flowering_prd',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='conservationthreat',
            name='threat_agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.threatagent'),
        ),
    ]
