# Generated by Django 3.2.20 on 2023-08-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0155_auto_20230804_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedingperiod',
            options={'ordering': ['period'], 'verbose_name': 'Breeding Period', 'verbose_name_plural': 'Breeding Periods'},
        ),
        migrations.AlterModelOptions(
            name='committeemembers',
            options={'verbose_name': 'Committee', 'verbose_name_plural': 'Committee Members'},
        ),
        migrations.AlterModelOptions(
            name='conservationcriteria',
            options={'ordering': ['code'], 'verbose_name': 'Conservation Criteria', 'verbose_name_plural': 'Conservation Criterias'},
        ),
        migrations.AlterModelOptions(
            name='conservationlist',
            options={'ordering': ['code'], 'verbose_name': 'Conservation List', 'verbose_name_plural': 'Conservation Lists'},
        ),
        migrations.AlterModelOptions(
            name='currentimpact',
            options={'verbose_name': 'Current Impact', 'verbose_name_plural': 'Current Impacts'},
        ),
        migrations.AlterModelOptions(
            name='florarecruitmenttype',
            options={'ordering': ['recruitment_type'], 'verbose_name': 'Flora Recruitment Type', 'verbose_name_plural': 'Flora Recruitment Types'},
        ),
        migrations.AlterModelOptions(
            name='floweringperiod',
            options={'ordering': ['period'], 'verbose_name': 'Flowering Period', 'verbose_name_plural': 'Flowering Periods'},
        ),
        migrations.AlterModelOptions(
            name='fruitingperiod',
            options={'ordering': ['period'], 'verbose_name': 'Fruiting Period', 'verbose_name_plural': 'Fruiting Periods'},
        ),
        migrations.AlterModelOptions(
            name='grouptype',
            options={'verbose_name': 'Group Type', 'verbose_name_plural': 'Group Types'},
        ),
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'ordering': ['room_name'], 'verbose_name': 'Meeting Room', 'verbose_name_plural': 'Meeting Rooms'},
        ),
        migrations.AlterModelOptions(
            name='postfirehabitatinteraction',
            options={'ordering': ['name'], 'verbose_name': 'Post Fire Habitat Interaction', 'verbose_name_plural': 'Post Fire Habitat Interactions'},
        ),
        migrations.AlterModelOptions(
            name='potentialimpact',
            options={'verbose_name': 'Potential Impact', 'verbose_name_plural': 'Potential Impacts'},
        ),
        migrations.AlterModelOptions(
            name='potentialthreatonset',
            options={'verbose_name': 'Potential Threat Onset', 'verbose_name_plural': 'Potential Threat Onsets'},
        ),
        migrations.AlterModelOptions(
            name='threatagent',
            options={'verbose_name': 'Threat Agent', 'verbose_name_plural': 'Threat Agents'},
        ),
        migrations.AlterField(
            model_name='conservationthreat',
            name='threat_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.threatcategory'),
        ),
    ]
