# Generated by Django 3.2.20 on 2023-08-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0156_auto_20230808_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='breeding_period',
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='flowering_period',
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='flowering_prd',
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='fruiting_period',
        ),
    ]
