# Generated by Django 3.2.20 on 2023-08-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0157_auto_20230809_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreedingPeriod',
        ),
        migrations.DeleteModel(
            name='FloweringPeriod',
        ),
        migrations.DeleteModel(
            name='FruitingPeriod',
        ),
    ]
