# Generated by Django 3.2.20 on 2023-08-09 08:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0158_auto_20230809_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='breeding_period',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='flowering_period',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='speciesconservationattributes',
            name='fruiting_period',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=250, null=True),
        ),
    ]
