# Generated by Django 3.2.20 on 2023-08-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0158_habitatcomposition_land_form'),
        ('boranga', '0159_auto_20230809_1600'),
    ]

    operations = [
    ]
