# Generated by Django 3.2.20 on 2023-09-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0160_auto_20230824_1549'),
        ('boranga', '0161_auto_20230825_1141'),
    ]

    operations = [
    ]
