# Generated by Django 3.2.20 on 2023-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0161_auto_20230816_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityconservationattributes',
            name='minimum_fire_interval',
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='minimum_fire_interval',
        ),
        migrations.AlterField(
            model_name='communityconservationattributes',
            name='minimum_fire_interval_choice',
            field=models.CharField(blank=True, choices=[(1, 'year/s'), (2, 'month/s')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='speciesconservationattributes',
            name='minimum_fire_interval_choice',
            field=models.CharField(blank=True, choices=[(1, 'year/s'), (2, 'month/s')], max_length=10, null=True),
        ),
    ]
