# Generated by Django 3.2.20 on 2023-09-07 01:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0164_auto_20230906_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitatcomposition',
            name='land_form',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
    ]
