# Generated by Django 3.2.20 on 2023-09-08 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0165_alter_habitatcomposition_land_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_conservation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.conservationcategory'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_conservation_criteria',
            field=models.ManyToManyField(blank=True, to='boranga.ConservationCriteria'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_conservation_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.conservationlist'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
    ]
