# Generated by Django 3.2.20 on 2023-09-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0162_auto_20230906_1640'),
        ('boranga', '0165_alter_habitatcomposition_land_form'),
    ]

    operations = [
    ]
