# Generated by Django 3.2.20 on 2023-09-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0166_auto_20230908_1530'),
        ('boranga', '0166_merge_20230908_1028'),
    ]

    operations = [
    ]
