# Generated by Django 3.2.20 on 2023-09-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0168_alter_firehistory_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_species', models.TextField(blank=True)),
                ('occurrence_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_species', to='boranga.occurrencereport', unique=True)),
            ],
        ),
    ]
