# Generated by Django 3.2.20 on 2023-09-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0169_associatedspecies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associatedspecies',
            old_name='associated_species',
            new_name='related_species',
        ),
    ]
