# Generated by Django 3.2.20 on 2023-09-13 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0170_rename_associated_species_associatedspecies_related_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Observation Method',
                'verbose_name_plural': 'Observation Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObservationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_surveyed', models.IntegerField(blank=True, default=0, null=True)),
                ('survey_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('observation_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.observationmethod')),
                ('occurrence_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obbservation_details', to='boranga.occurrencereport')),
            ],
        ),
    ]
