# Generated by Django 3.2.20 on 2023-09-13 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0171_observationdetails_observationmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Counted Subject',
                'verbose_name_plural': 'Counted Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ObservationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_surveyed', models.IntegerField(blank=True, default=0, null=True)),
                ('survey_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('observation_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.observationmethod')),
                ('occurrence_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observation_details', to='boranga.occurrencereport')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Plant Condition',
                'verbose_name_plural': 'Plant Conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_population_area', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_alive_mature', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_dead_mature', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_alive_juvenile', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_dead_juvenile', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_alive_seedling', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_dead_seedling', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_alive_unknown', models.IntegerField(blank=True, default=0, null=True)),
                ('detailed_dead_unknown', models.IntegerField(blank=True, default=0, null=True)),
                ('simple_alive', models.IntegerField(blank=True, default=0, null=True)),
                ('simple_dead', models.IntegerField(blank=True, default=0, null=True)),
                ('quadrats_present', models.BooleanField(blank=True, null=True)),
                ('quadrats_data_attached', models.BooleanField(blank=True, null=True)),
                ('quadrats_surveyed', models.IntegerField(blank=True, default=0, null=True)),
                ('individual_quadrat_area', models.IntegerField(blank=True, default=0, null=True)),
                ('total_quadrat_area', models.IntegerField(blank=True, default=0, null=True)),
                ('flowering_plants_per', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clonal_reproduction_present', models.BooleanField(blank=True, null=True)),
                ('vegetative_state_present', models.BooleanField(blank=True, null=True)),
                ('flower_bud_present', models.BooleanField(blank=True, null=True)),
                ('flower_present', models.BooleanField(blank=True, null=True)),
                ('immature_fruit_present', models.BooleanField(blank=True, null=True)),
                ('ripe_fruit_present', models.BooleanField(blank=True, null=True)),
                ('dehisced_fruit_present', models.BooleanField(blank=True, null=True)),
                ('pollinator_observation', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('counted_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.countedsubject')),
                ('occurrence_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_count', to='boranga.occurrencereport')),
                ('plant_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.plantcondition')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCountAccuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Plant Count Accuracy',
                'verbose_name_plural': 'Plant Count Accuracies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantCountMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Plant Count Method',
                'verbose_name_plural': 'Plant Count Methods',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='ObservationDetails',
        ),
        migrations.AddField(
            model_name='plantcount',
            name='plant_count_accuracy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.plantcountaccuracy'),
        ),
        migrations.AddField(
            model_name='plantcount',
            name='plant_count_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.plantcountmethod'),
        ),
    ]
