# Generated by Django 3.2.20 on 2023-10-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0172_auto_20231002_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='average_lifespan',
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='generation_length',
        ),
        migrations.RemoveField(
            model_name='speciesconservationattributes',
            name='time_to_maturity',
        ),
    ]
