# Generated by Django 3.2.20 on 2023-09-20 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0175_identification_identificationcertainty_permittype_sampledestination_sampletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Coordination Source',
                'verbose_name_plural': 'Coordination Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationAccuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Location Accuracy',
                'verbose_name_plural': 'Location Accuracy',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='identificationcertainty',
            options={'ordering': ['name'], 'verbose_name': 'Identification Certainty', 'verbose_name_plural': 'Identification Certainties'},
        ),
        migrations.CreateModel(
            name='ObserverDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('organisation', models.CharField(blank=True, max_length=250, null=True)),
                ('main_observer', models.BooleanField(blank=True, null=True)),
                ('occurrence_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observer_detail', to='boranga.occurrencereport', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateTimeField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('boundary_description', models.TextField(blank=True, null=True)),
                ('new_occurrence', models.BooleanField(blank=True, null=True)),
                ('boundry', models.IntegerField(blank=True, default=0, null=True)),
                ('mapped_boundry', models.BooleanField(blank=True, null=True)),
                ('buffer_radius', models.IntegerField(blank=True, default=0, null=True)),
                ('coordination_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.coordinationsource')),
                ('datum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.datum')),
                ('location_accuracy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.locationaccuracy')),
                ('occurrence_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='boranga.occurrencereport', unique=True)),
            ],
        ),
    ]
