# Generated by Django 3.2.20 on 2023-09-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0176_auto_20230920_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='boundry',
            new_name='boundary',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='mapped_boundry',
            new_name='mapped_boundary',
        ),
    ]
