# Generated by Django 3.2.20 on 2023-09-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0177_auto_20230920_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observerdetail',
            old_name='name',
            new_name='observer_name',
        ),
    ]
