# Generated by Django 3.2.20 on 2023-10-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0173_auto_20231002_1709'),
        ('boranga', '0179_alter_observerdetail_occurrence_report'),
    ]

    operations = [
    ]
