# Generated by Django 3.2.20 on 2023-10-10 01:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0179_alter_observerdetail_occurrence_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geojson_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
