# Generated by Django 3.2.20 on 2023-10-10 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0180_location_geojson_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geojson_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
