# Generated by Django 3.2.20 on 2023-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0180_merge_20231003_1108'),
        ('boranga', '0181_location_geojson_polygon'),
    ]

    operations = [
    ]
