# Generated by Django 3.2.20 on 2023-10-11 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0182_merge_20231010_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceReportGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('intersects', models.BooleanField(default=False)),
                ('drawn_by', models.IntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.occurrencereportgeometry')),
                ('occurrence_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_geometry', to='boranga.occurrencereport')),
            ],
        ),
    ]
