# Generated by Django 3.2.20 on 2023-10-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0183_occurrencereportgeometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='submitter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
