# Generated by Django 3.2.20 on 2024-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0185_occurrencereportlogdocument_occurrencereportlogentry_occurrencereportuseraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservationstatus',
            name='conservation_criteria',
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='conservation_criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='recommended_conservation_criteria',
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_conservation_criteria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
