# Generated by Django 3.2.23 on 2024-01-23 02:09

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0186_auto_20240112_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceReportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('document_number', models.CharField(blank=True, default='', max_length=9)),
                ('_file', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('document_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentcategory')),
                ('document_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.documentsubcategory')),
                ('occurrence_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='boranga.occurrencereport')),
            ],
            options={
                'verbose_name': 'Occurrence Report Document',
            },
        ),
    ]
