# Generated by Django 3.2.23 on 2024-01-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0187_occurrencereportdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereportdocument',
            name='added_by',
            field=models.IntegerField(null=True),
        ),
    ]
