# Generated by Django 3.2.23 on 2024-02-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0190_ocrconservationthreat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityName',
        ),
        migrations.DeleteModel(
            name='FaunaBreeding',
        ),
        migrations.DeleteModel(
            name='PollinatorInformation',
        ),
        migrations.DeleteModel(
            name='SeedViabilityGerminationInfo',
        ),
    ]
