# Generated by Django 3.2.23 on 2024-02-12 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0191_auto_20240209_1323'),
    ]

    operations = [

    ]
