# Generated by Django 3.2.23 on 2024-02-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0192_auto_20240212_1118'),
    ]

    operations = []
