# Generated by Django 3.2.23 on 2024-02-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0193_auto_20240213_0935'),
    ]

    operations = []
