# Generated by Django 3.2.23 on 2024-02-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0194_auto_20240213_1032'),
    ]

    operations = [

    ]
