# Generated by Django 3.2.23 on 2024-02-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0194_auto_20240213_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvaldocument',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='approvallogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='approvallogentry',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='approvallogentry',
            name='communicationslogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='approvaluseraction',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='previewtempapproval',
            name='approval_ptr',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='approval',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='ApprovalDocument',
        ),
        migrations.DeleteModel(
            name='ApprovalLogDocument',
        ),
        migrations.DeleteModel(
            name='ApprovalLogEntry',
        ),
        migrations.DeleteModel(
            name='ApprovalUserAction',
        ),
        migrations.DeleteModel(
            name='PreviewTempApproval',
        ),
    ]
