# Generated by Django 3.2.23 on 2024-02-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0195_auto_20240213_1039'),
    ]

    operations = []
