# Generated by Django 3.2.23 on 2024-02-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0196_auto_20240213_1406'),
    ]

    operations = []
