# Generated by Django 3.2.23 on 2024-02-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0197_auto_20240213_1520'),
    ]

    operations = []
