# Generated by Django 3.2.23 on 2024-02-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0197_auto_20240213_1520'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationAccessGroup',
        ),
        migrations.RemoveField(
            model_name='organisationaction',
            name='organisation',
        ),
        migrations.AlterUniqueTogether(
            name='organisationcontact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organisationcontact',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='organisationcontactdeclineddetails',
            name='request',
        ),
        migrations.RemoveField(
            model_name='organisationlogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='organisationlogentry',
            name='communicationslogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='organisationlogentry',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='organisationrequestdeclineddetails',
            name='request',
        ),
        migrations.RemoveField(
            model_name='organisationrequestlogdocument',
            name='log_entry',
        ),
        migrations.RemoveField(
            model_name='organisationrequestlogentry',
            name='communicationslogentry_ptr',
        ),
        migrations.RemoveField(
            model_name='organisationrequestlogentry',
            name='request',
        ),
        migrations.RemoveField(
            model_name='organisationrequestuseraction',
            name='request',
        ),
        migrations.AlterUniqueTogether(
            name='userdelegation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userdelegation',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='OrganisationAction',
        ),
        migrations.DeleteModel(
            name='OrganisationContact',
        ),
        migrations.DeleteModel(
            name='OrganisationContactDeclinedDetails',
        ),
        migrations.DeleteModel(
            name='OrganisationLogDocument',
        ),
        migrations.DeleteModel(
            name='OrganisationLogEntry',
        ),
        migrations.DeleteModel(
            name='OrganisationRequest',
        ),
        migrations.DeleteModel(
            name='OrganisationRequestDeclinedDetails',
        ),
        migrations.DeleteModel(
            name='OrganisationRequestLogDocument',
        ),
        migrations.DeleteModel(
            name='OrganisationRequestLogEntry',
        ),
        migrations.DeleteModel(
            name='OrganisationRequestUserAction',
        ),
        migrations.DeleteModel(
            name='UserDelegation',
        ),
    ]
