# Generated by Django 3.2.23 on 2024-02-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0199_auto_20240214_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservationstatus',
            name='proposed_issuance_approval',
        ),
    ]
