# Generated by Django 3.2.23 on 2024-02-16 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0200_remove_conservationstatus_proposed_issuance_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatedspecies',
            name='occurrence_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_species', to='boranga.occurrencereport'),
        ),
        migrations.AlterField(
            model_name='firehistory',
            name='occurrence_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_history', to='boranga.occurrencereport'),
        ),
        migrations.AlterField(
            model_name='habitatcomposition',
            name='occurrence_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitat_composition', to='boranga.occurrencereport'),
        ),
        migrations.AlterField(
            model_name='habitatcondition',
            name='occurrence_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitat_condition', to='boranga.occurrencereport'),
        ),
        migrations.AlterField(
            model_name='location',
            name='occurrence_report',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='boranga.occurrencereport'),
        ),
    ]
