# Generated by Django 3.2.23 on 2024-02-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0201_auto_20240216_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='IUCNVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='None', max_length=32)),
                ('label', models.CharField(default='None', max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='cs_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='cs_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='delisting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='review_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='reviewed_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='iucn_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iucn_version', to='boranga.iucnversion'),
        ),
    ]
