# Generated by Django 3.2.23 on 2024-03-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0202_auto_20240216_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitydistribution',
            name='number_of_iucn_subpopulations',
        ),
        migrations.AddField(
            model_name='communitydistribution',
            name='distribution',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='speciesdistribution',
            name='distribution',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
