# Generated by Django 3.2.23 on 2024-03-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0203_occurrencereportgeometry_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrencereportgeometry',
            old_name='points',
            new_name='point',
        ),
    ]
