# Generated by Django 3.2.23 on 2024-03-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0204_auto_20240306_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitydistribution',
            name='area_of_occupancy_actual',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='communitydistribution',
            name='community_original_area_accuracy',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='speciesdistribution',
            name='area_of_occupancy_actual',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
