# Generated by Django 3.2.23 on 2024-03-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0204_rename_points_occurrencereportgeometry_point'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='occurrencereportgeometry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('polygon__isnull', False)), models.Q(('point__isnull', False)), _connector='OR'), name='point_and_polygon_mutually_exclusive'),
        ),
    ]
