# Generated by Django 3.2.23 on 2024-03-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0205_occurrencereportgeometry_point_and_polygon_mutually_exclusive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='occurrencereportgeometry',
            name='point_and_polygon_mutually_exclusive',
        ),
        migrations.AddConstraint(
            model_name='occurrencereportgeometry',
            constraint=models.CheckConstraint(check=models.Q(('point__isnull', False), ('polygon__isnull', False), _negated=True), name='point_and_polygon_mutually_exclusive'),
        ),
    ]
