# Generated by Django 3.2.23 on 2024-03-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0205_auto_20240306_1613'),
        ('boranga', '0206_auto_20240321_0904'),
    ]

    operations = [
    ]
