# Generated by Django 3.2.25 on 2024-03-26 01:47

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0207_merge_0205_auto_20240306_1613_0206_auto_20240321_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceReportShapefileDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('occurrence_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_documents', to='boranga.occurrencereport')),
            ],
        ),
    ]
