# Generated by Django 3.2.25 on 2024-03-28 08:14

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0208_occurrencereportshapefiledocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_number', models.CharField(blank=True, default='', max_length=9)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('locked', 'Locked'), ('split', 'Split'), ('combine', 'Combine'), ('historical', 'Historical')], default='draft', max_length=30, verbose_name='Processing Status')),
                ('group_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.grouptype')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.species')),
            ],
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['group_type'], name='boranga_occ_group_t_80a151_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['species'], name='boranga_occ_species_c749f0_idx'),
        ),
    ]
