# Generated by Django 3.2.25 on 2024-03-28 08:18

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0209_add_occurence_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occurrence",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
