# Generated by Django 3.2.25 on 2024-04-02 01:38

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0210_add_created_update_fields_to_occurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="submitter",
            field=models.IntegerField(null=True),
        ),
    ]
