# Generated by Django 3.2.25 on 2024-04-02 08:47

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0211_add_submitter_field_to_occurrence"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceUserAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who", models.IntegerField()),
                ("when", models.DateTimeField(auto_now_add=True)),
                ("what", models.TextField()),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="boranga.occurrence",
                    ),
                ),
            ],
            options={
                "ordering": ("-when",),
            },
        ),
        migrations.CreateModel(
            name="OccurrenceLogEntry",
            fields=[
                (
                    "communicationslogentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boranga.communicationslogentry",
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comms_logs",
                        to="boranga.occurrence",
                    ),
                ),
            ],
            bases=("boranga.communicationslogentry",),
        ),
        migrations.CreateModel(
            name="OccurrenceLogDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "_file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/private-media/",
                            location="/data/data/projects/boranga/private-media/",
                        ),
                        upload_to=boranga.components.occurrence.models.update_occurrence_comms_log_filename,
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="boranga.occurrencelogentry",
                    ),
                ),
            ],
        ),
    ]
