# Generated by Django 3.2.25 on 2024-04-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0212_create_occurrence_logging_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereport",
            name="occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrence_report",
                to="boranga.occurrence",
            ),
        ),
    ]
