# Generated by Django 3.2.25 on 2024-04-03 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0213_add_occurence_fk_to_occurrence_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrences",
                to="boranga.community",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="species",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrences",
                to="boranga.species",
            ),
        ),
    ]
