# Generated by Django 3.2.25 on 2024-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0214_add_community_field_to_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='epsg_code',
            field=models.IntegerField(blank=True, default=4326, null=True),
        ),
    ]
