# Generated by Django 3.2.25 on 2024-04-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0214_add_community_field_to_occurrence'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='occurrencereportgeometry',
            constraint=models.CheckConstraint(check=models.Q(('occurrence_report__group_type', 'fauna'), ('polygon__isnull', False), _negated=True), name='fauna_map_utilises_points_only'),
        ),
    ]
