# Generated by Django 3.2.25 on 2024-04-11 05:41

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0216_alter_location_epsg_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceReportProposalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True)),
                ('officer', models.IntegerField(null=True)),
                ('occurrence_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.occurrencereport')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceReportReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodged_on', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.IntegerField()),
                ('referral', models.IntegerField()),
                ('linked', models.BooleanField(default=False)),
                ('sent_from', models.SmallIntegerField(choices=[(1, 'Sent From Assessor'), (2, 'Sent From Referral')], default=1)),
                ('processing_status', models.CharField(choices=[('with_referral', 'Awaiting'), ('recalled', 'Recalled'), ('completed', 'Completed')], default='with_referral', max_length=30, verbose_name='Processing Status')),
                ('text', models.TextField(blank=True)),
                ('referral_text', models.TextField(blank=True)),
                ('referral_comment', models.TextField(blank=True, null=True)),
                ('assigned_officer', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('-lodged_on',),
            },
        ),
        migrations.CreateModel(
            name='OccurrenceReportAmendmentRequest',
            fields=[
                ('occurrencereportproposalrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boranga.occurrencereportproposalrequest')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('amended', 'Amended')], default='requested', max_length=30, verbose_name='Status')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.proposalamendmentreason')),
            ],
            bases=('boranga.occurrencereportproposalrequest',),
        ),
        migrations.CreateModel(
            name='OccurrenceReportReferralDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_referral_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_documents', to='boranga.occurrencereportreferral')),
            ],
        ),
        migrations.AddField(
            model_name='occurrencereportreferral',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_document', to='boranga.occurrencereportreferraldocument'),
        ),
        migrations.AddField(
            model_name='occurrencereportreferral',
            name='ocurrence_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='boranga.occurrencereport'),
        ),
        migrations.CreateModel(
            name='OccurrenceReportAmendmentRequestDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.occurrence.models.update_occurrence_report_amendment_request_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('occurrence_report_amendment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_request_documents', to='boranga.occurrencereportamendmentrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
