# Generated by Django 3.2.25 on 2024-04-12 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0217_occurrence_report_amendment_referral_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
