# Generated by Django 3.2.25 on 2024-04-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0218_add_review_fields_occurrence_and_occurrence_report'),
        ('boranga', '0218_occurrencereportgeometry_geometry'),
    ]

    operations = [
    ]
