# Generated by Django 3.2.25 on 2024-04-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0218_add_review_fields_occurrence_and_occurrence_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observerdetail',
            name='observer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='observerdetail',
            unique_together={('observer_name', 'occurrence_report')},
        ),
    ]
