# Generated by Django 3.2.25 on 2024-04-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0219_auto_20240415_1114'),
        ('boranga', '0219_merge_20240415_1356'),
    ]

    operations = [
    ]
