# Generated by Django 3.2.25 on 2024-04-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0219_auto_20240415_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Wild Status',
                'verbose_name_plural': 'Wild Statuses',
                'ordering': ['name'],
            },
        ),
    ]
