# Generated by Django 3.2.25 on 2024-04-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0220_merge_20240417_0943'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='occurrencereportgeometry',
            name='point_and_polygon_mutually_exclusive',
        ),
        migrations.RemoveField(
            model_name='occurrencereportgeometry',
            name='point',
        ),
        migrations.RemoveField(
            model_name='occurrencereportgeometry',
            name='polygon',
        ),
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='original_geometry_ewkb',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
