# Generated by Django 3.2.25 on 2024-04-16 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0220_add_wild_status_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='wild_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.wildstatus'),
        ),
    ]
