# Generated by Django 3.2.25 on 2024-04-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0221_auto_20240417_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='original_geometry_ewkb',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
