# Generated by Django 3.2.25 on 2024-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0221_add_wild_status_field_to_occurrence_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='occurrence_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
