# Generated by Django 3.2.25 on 2024-04-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0221_occconservationthreat'),
        ('boranga', '0222_add_occurrence_name_field_to_occurrence'),
    ]

    operations = [
    ]
