# Generated by Django 3.2.25 on 2024-04-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0222_alter_occurrencereportgeometry_original_geometry_ewkb'),
        ('boranga', '0223_merge_20240417_1423'),
    ]

    operations = [
    ]
