# Generated by Django 3.2.25 on 2024-04-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0223_merge_20240417_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Occurrence Source',
                'verbose_name_plural': 'Occurrence Sources',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.occurrencesource'),
        ),
    ]
