# Generated by Django 3.2.25 on 2024-04-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0224_auto_20240419_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='occurrence',
            new_name='occurrence_source',
        ),
    ]
