# Generated by Django 3.2.25 on 2024-04-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0224_merge_20240419_1552'),
        ('boranga', '0225_add_occurrence_repoert_declined_details_model'),
    ]

    operations = [
    ]
