# Generated by Django 3.2.25 on 2024-04-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0224_merge_20240419_1552'),
        ('boranga', '0225_rename_occurrence_occurrence_occurrence_source'),
    ]

    operations = [
    ]
