# Generated by Django 3.2.25 on 2024-04-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0226_merge_20240419_1620"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceReportApprovalDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("officer", models.IntegerField()),
                ("effective_from_date", models.DateField(blank=True, null=True)),
                ("effective_to_date", models.DateField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                (
                    "occurrence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boranga.occurrence",
                    ),
                ),
                (
                    "occurrence_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_details",
                        to="boranga.occurrencereport",
                    ),
                ),
            ],
        ),
    ]
