# Generated by Django 3.2.25 on 2024-04-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0227_add_occurrence_report_approval_details_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereportapprovaldetails",
            name="occurrence",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.occurrence",
            ),
        ),
    ]
