# Generated by Django 3.2.25 on 2024-04-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0227_occurrence_comment'),
        ('boranga', '0228_make_occurrence_nullable_on_approval_details'),
    ]

    operations = [
    ]
