# Generated by Django 3.2.25 on 2024-04-29 02:18

import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0229_merge_20240422_1409"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUserAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who", models.IntegerField()),
                ("when", models.DateTimeField(auto_now_add=True)),
                ("what", models.TextField()),
                ("email_user", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="EmailUserLogEntry",
            fields=[
                (
                    "communicationslogentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="boranga.communicationslogentry",
                    ),
                ),
                ("email_user", models.IntegerField()),
            ],
            bases=("boranga.communicationslogentry",),
        ),
        migrations.AlterField(
            model_name="occurrencereportdeclineddetails",
            name="occurrence_report",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="declined_details",
                to="boranga.occurrencereport",
            ),
        ),
        migrations.CreateModel(
            name="EmailUserLogDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "_file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/private-media/",
                            location="/home/oak/dev/boranga/private-media/",
                        ),
                        upload_to=boranga.components.users.models.email_user_comms_log_document_upload_location,
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="boranga.emailuserlogentry",
                    ),
                ),
            ],
        ),
    ]
