# Generated by Django 3.2.25 on 2024-04-26 08:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0230_alter_occurrencereportdeclineddetails_occurrence_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.5, -17.5, 129.0, -31.5), null=True, srid=4326),
        ),
    ]
