# Generated by Django 3.2.25 on 2024-04-26 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0231_auto_20240426_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occconservationthreat',
            name='occurrence_report',
        ),
        migrations.AddField(
            model_name='occconservationthreat',
            name='occurrence_report_threat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_report_threat', to='boranga.ocrconservationthreat'),
        ),
    ]
