# Generated by Django 3.2.25 on 2024-04-29 06:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0231_alter_occurrencereportgeometry_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.5, -35.5, 129.0, -13.5), null=True, srid=4326),
        ),
    ]
