# Generated by Django 3.2.25 on 2024-04-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0232_auto_20240426_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occconservationthreat',
            unique_together={('occurrence', 'occurrence_report_threat')},
        ),
    ]
