# Generated by Django 3.2.25 on 2024-04-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0230_add_user_logging_models'),
        ('boranga', '0233_alter_occconservationthreat_unique_together'),
    ]

    operations = [
    ]
