# Generated by Django 3.2.25 on 2024-04-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0234_merge_20240429_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportapprovaldetails",
            name="new_occurrence_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
