# Generated by Django 3.2.25 on 2024-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0236_auto_20240429_1358"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="conservation_plan_exists",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="community",
            name="conservation_plan_reference",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="conservation_plan_exists",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="species",
            name="conservation_plan_reference",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
