# Generated by Django 3.2.25 on 2024-04-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0232_alter_occurrencereportgeometry_geometry'),
        ('boranga', '0237_auto_20240429_1519'),
    ]

    operations = [
    ]
