# Generated by Django 3.2.25 on 2024-05-08 05:48

import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0241_auto_20240503_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.users.models.email_user_comms_log_document_upload_location),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='processing_status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('split', 'Split'), ('combine', 'Combine'), ('historical', 'Historical')], default='active', max_length=30, verbose_name='Processing Status'),
        ),
    ]
