# Generated by Django 3.2.25 on 2024-05-08 06:31

import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0241_auto_20240503_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='path',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='previous_name',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='class_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='family_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='family_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='genera_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='genera_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='emailuserlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/boranga/private-media/'), upload_to=boranga.components.users.models.email_user_comms_log_document_upload_location),
        ),
        migrations.CreateModel(
            name='TaxonPreviousName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_name_id', models.IntegerField(blank=True, null=True)),
                ('previous_scientific_name', models.CharField(blank=True, max_length=512, null=True)),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_names', to='boranga.taxonomy')),
            ],
        ),
    ]
