# Generated by Django 3.2.25 on 2024-05-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0242_auto_20240508_1348'),
        ('boranga', '0242_auto_20240508_1431'),
    ]

    operations = [
    ]
