# Generated by Django 3.2.25 on 2024-05-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0245_auto_20240513_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesPublishingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_public', models.BooleanField(default=False)),
                ('distribution_public', models.BooleanField(default=False)),
                ('conservation_status_public', models.BooleanField(default=False)),
                ('conservation_attributes_public', models.BooleanField(default=False)),
                ('threats_public', models.BooleanField(default=False)),
                ('species', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_publishing_status', to='boranga.species')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPublishingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_public', models.BooleanField(default=False)),
                ('distribution_public', models.BooleanField(default=False)),
                ('conservation_status_public', models.BooleanField(default=False)),
                ('conservation_attributes_public', models.BooleanField(default=False)),
                ('threats_public', models.BooleanField(default=False)),
                ('community', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_publishing_status', to='boranga.community')),
            ],
        ),
    ]
