# Generated by Django 3.2.25 on 2024-05-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0245_auto_20240513_1412"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_user", models.IntegerField()),
                (
                    "organisation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boranga.usercategory",
                    ),
                ),
            ],
        ),
    ]
