# Generated by Django 3.2.25 on 2024-05-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0244_auto_20240514_1547'),
        ('boranga', '0246_auto_20240513_1413'),
    ]

    operations = [
    ]
