# Generated by Django 3.2.25 on 2024-05-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0248_auto_20240515_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonwealthConservationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=512)),
                ('applies_to_species', models.BooleanField(default=False)),
                ('applies_to_communities', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WAConservationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=512)),
                ('applies_to_species', models.BooleanField(default=False)),
                ('applies_to_communities', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WALegislativeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=512)),
                ('applies_to_species', models.BooleanField(default=False)),
                ('applies_to_communities', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WAPriorityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=512)),
                ('applies_to_species', models.BooleanField(default=False)),
                ('applies_to_communities', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WAPriorityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=512)),
                ('applies_to_species', models.BooleanField(default=False)),
                ('applies_to_communities', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='conservation_category',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='conservation_list',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='recommended_conservation_category',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='recommended_conservation_list',
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='international_conservation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_international_conservation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='commonwealth_conservation_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_commonwealth_conservation_list', to='boranga.commonwealthconservationlist'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_commonwealth_conservation_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.commonwealthconservationlist'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_wa_conservation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.waconservationcategory'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_wa_legislative_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.walegislativelist'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_wa_priority_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.waprioritycategory'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_wa_priority_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.waprioritylist'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='wa_conservation_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_wa_conservation_category', to='boranga.waconservationcategory'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='wa_legislative_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_wa_legislative_list', to='boranga.walegislativelist'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='wa_priority_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_wa_priority_category', to='boranga.waprioritycategory'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='wa_priority_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_wa_priority_list', to='boranga.waprioritylist'),
        ),
    ]
