# Generated by Django 3.2.25 on 2024-05-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0245_communitypublishingstatus_speciespublishingstatus'),
        ('boranga', '0248_auto_20240515_1235'),
    ]

    operations = [
    ]
