# Generated by Django 3.2.25 on 2024-05-17 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0249_auto_20240516_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='WALegislativeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'WA Legislative Category',
                'verbose_name_plural': 'WA Legislative Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='commonwealthconservationlist',
            options={'verbose_name': 'Commonwealth Conservation List'},
        ),
        migrations.AlterModelOptions(
            name='walegislativelist',
            options={'verbose_name': 'WA Legislative List'},
        ),
        migrations.AlterModelOptions(
            name='waprioritycategory',
            options={'verbose_name': 'WA Priority Category', 'verbose_name_plural': 'WA Priority Categories'},
        ),
        migrations.AlterModelOptions(
            name='waprioritylist',
            options={'verbose_name': 'WA Priority List'},
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='recommended_wa_conservation_category',
        ),
        migrations.RemoveField(
            model_name='conservationstatus',
            name='wa_conservation_category',
        ),
        migrations.RemoveField(
            model_name='waprioritycategory',
            name='applies_to_communities',
        ),
        migrations.RemoveField(
            model_name='waprioritycategory',
            name='applies_to_species',
        ),
        migrations.AddField(
            model_name='waprioritycategory',
            name='wa_priority_lists',
            field=models.ManyToManyField(to='boranga.WAPriorityList'),
        ),
        migrations.DeleteModel(
            name='WAConservationCategory',
        ),
        migrations.AddField(
            model_name='walegislativecategory',
            name='wa_legislative_lists',
            field=models.ManyToManyField(to='boranga.WALegislativeList'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='recommended_wa_legislative_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.walegislativecategory'),
        ),
        migrations.AddField(
            model_name='conservationstatus',
            name='wa_legislative_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_wa_legislative_category', to='boranga.walegislativecategory'),
        ),
    ]
