# Generated by Django 3.2.25 on 2024-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0249_merge_20240516_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationthreat',
            name='comment',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='occconservationthreat',
            name='comment',
            field=models.CharField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ocrconservationthreat',
            name='comment',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
