# Generated by Django 3.2.25 on 2024-05-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0249_merge_20240516_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['scientific_name'], 'verbose_name': 'Taxonomy', 'verbose_name_plural': 'Taxonomies'},
        ),
        migrations.RemoveField(
            model_name='classificationsystem',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='informalgroup',
            name='informal_group_id',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='family_fk',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='family_nid',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='genus',
        ),
    ]
