# Generated by Django 3.2.25 on 2024-05-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0250_auto_20240517_0900"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonwealthconservationlist",
            options={
                "ordering": ["code"],
                "verbose_name": "Commonwealth Conservation List",
            },
        ),
        migrations.AlterModelOptions(
            name="walegislativecategory",
            options={
                "ordering": ["code"],
                "verbose_name": "WA Legislative Category",
                "verbose_name_plural": "WA Legislative Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="walegislativelist",
            options={"ordering": ["code"], "verbose_name": "WA Legislative List"},
        ),
        migrations.AlterModelOptions(
            name="waprioritycategory",
            options={
                "ordering": ["code"],
                "verbose_name": "WA Priority Category",
                "verbose_name_plural": "WA Priority Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="waprioritylist",
            options={"ordering": ["code"], "verbose_name": "WA Priority List"},
        ),
        migrations.AddField(
            model_name="conservationstatus",
            name="approval_level",
            field=models.CharField(
                choices=[("intermediate", "Intermediate"), ("minister", "Minister")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="walegislativecategory",
            name="wa_legislative_lists",
            field=models.ManyToManyField(
                related_name="wa_legislative_categories", to="boranga.WALegislativeList"
            ),
        ),
        migrations.AlterField(
            model_name="waprioritycategory",
            name="wa_priority_lists",
            field=models.ManyToManyField(
                related_name="wa_priority_categories", to="boranga.WAPriorityList"
            ),
        ),
    ]
