# Generated by Django 3.2.25 on 2024-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0250_auto_20240516_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationthreat',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='occconservationthreat',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
