# Generated by Django 3.2.25 on 2024-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0251_auto_20240520_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationchangecode",
            name="code",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="conservationchangecode",
            name="label",
            field=models.CharField(max_length=512),
        ),
    ]
