# Generated by Django 3.2.25 on 2024-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0251_auto_20240516_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrconservationthreat',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
