# Generated by Django 3.2.25 on 2024-05-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0252_auto_20240520_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conservationcriteria',
            name='conservation_list',
        ),
        migrations.DeleteModel(
            name='ConservationCategory',
        ),
        migrations.DeleteModel(
            name='ConservationCriteria',
        ),
        migrations.DeleteModel(
            name='ConservationList',
        ),
    ]
