# Generated by Django 3.2.25 on 2024-05-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0250_auto_20240516_1645'),
        ('boranga', '0252_alter_ocrconservationthreat_comment'),
    ]

    operations = [
    ]
