# Generated by Django 3.2.25 on 2024-05-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0253_merge_20240516_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoserverUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('wms_version', models.CharField(default='1.3.0', max_length=10)),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='TileLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255, unique=True)),
                ('layer_title', models.CharField(max_length=255)),
                ('display_title', models.CharField(max_length=255)),
                ('is_satellite_background', models.BooleanField(default=False)),
                ('is_streets_background', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=True)),
                ('is_internal', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=False)),
                ('geoserver_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boranga.geoserverurl')),
            ],
            options={
                'ordering': ['display_title', 'layer_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='tilelayer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_satellite_background', True), ('is_streets_background', True), _negated=True)), name='tilelayer_is_either_satellite_or_streets_background_or_neither'),
        ),
    ]
