# Generated by Django 3.2.25 on 2024-05-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0253_merge_20240516_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.CharField(choices=[('flora', 'Flora'), ('fauna', 'Fauna'), ('community', 'Community')], default=('fauna', 'Fauna'), max_length=64, verbose_name='GroupType Name'),
        ),
    ]
