# Generated by Django 3.2.25 on 2024-05-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0254_auto_20240517_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoserverurl',
            options={'ordering': ['url'], 'verbose_name': 'Geoserver URL', 'verbose_name_plural': 'Geoserver URLs'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={'ordering': ['display_title', 'layer_name'], 'verbose_name': 'Geoserver Tile Layer', 'verbose_name_plural': 'Geoserver Tile Layers'},
        ),
        migrations.AddField(
            model_name='tilelayer',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
