# Generated by Django 3.2.25 on 2024-05-20 08:05

from django.db import migrations
from django.core.management import call_command


fixtures_path = "boranga/components/spatial/fixtures/"


def loaddata_geoserverurl(apps, schema_editor):
    call_command(
        "loaddata", fixtures_path + "geoserverurl.2024-08-09.json", verbosity=0
    )


def loaddata_tilelayer(apps, schema_editor):
    call_command("loaddata", fixtures_path + "tilelayer.2024-06-13.json", verbosity=0)


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0255_auto_20240517_1049"),
    ]

    operations = [
        migrations.RunPython(loaddata_geoserverurl),
        migrations.RunPython(loaddata_tilelayer),
    ]
