# Generated by Django 3.2.25 on 2024-05-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0254_alter_grouptype_name'),
        ('boranga', '0254_auto_20240521_1029'),
        ('boranga', '0256_loaddata_geoserverurl_and_tilelayer'),
    ]

    operations = [
    ]
