# Generated by Django 3.2.25 on 2024-05-23 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0257_merge_20240522_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='observation_date',
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.district'),
        ),
        migrations.AddField(
            model_name='location',
            name='locality',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.region'),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='observation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='processing_status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('split', 'Split'), ('combine', 'Combine'), ('historical', 'Historical'), ('discarded', 'Discarded')], default='active', max_length=30, verbose_name='Processing Status'),
        ),
    ]
