# Generated by Django 3.2.25 on 2024-05-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0257_merge_20240522_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='processing_status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('split', 'Split'), ('combine', 'Combine'), ('historical', 'Historical'), ('discarded', 'Discarded')], default='active', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.CreateModel(
            name='OCRVegetationStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text_field_one', models.TextField(blank=True, null=True)),
                ('free_text_field_two', models.TextField(blank=True, null=True)),
                ('free_text_field_three', models.TextField(blank=True, null=True)),
                ('free_text_field_four', models.TextField(blank=True, null=True)),
                ('occurrence_report', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_structure', to='boranga.occurrencereport')),
            ],
        ),
        migrations.CreateModel(
            name='OCCVegetationStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_text_field_one', models.TextField(blank=True, null=True)),
                ('free_text_field_two', models.TextField(blank=True, null=True)),
                ('free_text_field_three', models.TextField(blank=True, null=True)),
                ('free_text_field_four', models.TextField(blank=True, null=True)),
                ('occurrence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_structure', to='boranga.occurrence')),
            ],
        ),
    ]
