# Generated by Django 3.2.25 on 2024-05-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0254_auto_20240523_1647'),
        ('boranga', '0258_auto_20240523_1123'),
    ]

    operations = [
    ]
