# Generated by Django 3.2.25 on 2024-05-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0258_auto_20240523_1123'),
        ('boranga', '0258_auto_20240523_1541'),
    ]

    operations = [
    ]
