# Generated by Django 3.2.25 on 2024-05-24 02:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0259_merge_0258_auto_20240523_1123_0258_auto_20240523_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='OCRLocation',
        ),
        migrations.CreateModel(
            name='OCCLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_description', models.TextField(blank=True, null=True)),
                ('boundary_description', models.TextField(blank=True, null=True)),
                ('boundary', models.IntegerField(blank=True, default=0, null=True)),
                ('mapped_boundary', models.BooleanField(blank=True, null=True)),
                ('buffer_radius', models.IntegerField(blank=True, default=0, null=True)),
                ('epsg_code', models.IntegerField(default=4326)),
                ('geojson_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geojson_polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('locality', models.TextField(blank=True, default=None, null=True)),
                ('coordination_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.coordinationsource')),
                ('datum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.datum')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.district')),
                ('location_accuracy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.locationaccuracy')),
                ('occurrence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='boranga.occurrence')),
                ('region', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.region')),
            ],
        ),
    ]
