# Generated by Django 3.2.25 on 2024-05-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0259_merge_0254_auto_20240523_1647_0258_auto_20240523_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationstatus",
            name="effective_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="conservationstatus",
            name="effective_to",
            field=models.DateField(blank=True, null=True),
        ),
    ]
