# Generated by Django 3.2.25 on 2024-05-24 06:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0260_auto_20240524_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.5, -35.5, 129.0, -13.5), null=True, srid=4326)),
                ('original_geometry_ewkb', models.BinaryField(blank=True, editable=True, null=True)),
                ('intersects', models.BooleanField(default=False)),
                ('drawn_by', models.IntegerField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.occurrencegeometry')),
                ('occurrence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occ_geometry', to='boranga.occurrence')),
            ],
        ),
    ]
