# Generated by Django 3.2.25 on 2024-05-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0259_merge_0258_auto_20240523_1123_0258_auto_20240523_1541'),
        ('boranga', '0260_auto_20240524_1128'),
    ]

    operations = [
    ]
