# Generated by Django 3.2.25 on 2024-05-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0261_merge_20240524_1213'),
        ('boranga', '0261_occurrencegeometry'),
    ]

    operations = [
    ]
