# Generated by Django 3.2.25 on 2024-05-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0262_merge_20240527_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='species_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.taxonomy'),
        ),
        migrations.AddField(
            model_name='occurrencereport',
            name='species_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.taxonomy'),
        ),
    ]
