# Generated by Django 3.2.25 on 2024-05-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0262_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoserverurl',
            name='requires_basic_auth',
            field=models.BooleanField(default=False),
        ),
    ]
