# Generated by Django 3.2.25 on 2024-05-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0263_geoserverurl_requires_basic_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='disabled',
        ),
        migrations.AddField(
            model_name='proxy',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
