# Generated by Django 3.2.25 on 2024-05-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0263_auto_20240527_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='species_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='boranga.taxonomy'),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='species_taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_reports', to='boranga.taxonomy'),
        ),
    ]
