# Generated by Django 3.2.25 on 2024-05-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0262_auto_20240528_1427'),
        ('boranga', '0264_auto_20240527_1605'),
    ]

    operations = [
    ]
