# Generated by Django 3.2.25 on 2024-05-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0265_auto_20240529_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tilelayer',
            name='disabled',
        ),
        migrations.AddField(
            model_name='tilelayer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
