# Generated by Django 3.2.25 on 2024-05-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0265_merge_0262_auto_20240528_1427_0264_auto_20240527_1605'),
        ('boranga', '0266_auto_20240529_1510'),
    ]

    operations = [
    ]
