# Generated by Django 3.2.25 on 2024-05-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0267_merge_20240529_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='boranga.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
