# Generated by Django 3.2.25 on 2024-05-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0268_auto_20240530_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='archive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='forest_region',
            field=models.BooleanField(default=False),
        ),
    ]
