# Generated by Django 3.2.25 on 2024-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0268_auto_20240529_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitterinformation",
            name="contact_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submitterinformation",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
