# Generated by Django 3.2.25 on 2024-05-30 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0270_auto_20240530_0923"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitterinformation",
            name="submitter_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.submittercategory",
            ),
        ),
    ]
