# Generated by Django 3.2.25 on 2024-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0272_auto_20240530_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="submitterinformation",
            name="email_user",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
