# Generated by Django 3.2.25 on 2024-05-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0273_auto_20240530_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilelayer',
            name='invert_xy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tilelayer',
            name='is_tenure_intersects_query_layer',
            field=models.BooleanField(default=False),
        ),
    ]
