# Generated by Django 3.2.25 on 2024-05-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0273_auto_20240530_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="species_taxonomy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conservation_statuses",
                to="boranga.taxonomy",
            ),
        ),
    ]
