# Generated by Django 3.2.25 on 2024-06-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0274_auto_20240530_1522'),
        ('boranga', '0274_auto_20240531_1355'),
    ]

    operations = [
    ]
