# Generated by Django 3.2.25 on 2024-06-04 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0274_auto_20240531_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencereport',
            name='species_taxonomy',
        ),
    ]
