# Generated by Django 3.2.25 on 2024-06-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0275_remove_occurrencereport_species_taxonomy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='species_taxonomy',
        ),
    ]
