# Generated by Django 3.2.25 on 2024-06-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0269_auto_20240530_1050'),
        ('boranga', '0275_merge_0274_auto_20240530_1522_0274_auto_20240531_1355'),
    ]

    operations = [
    ]
