# Generated by Django 3.2.25 on 2024-06-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0275_occurrencetenure_occurrencetenurepurpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencetenure',
            name='occurrence_geometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_tenures', to='boranga.occurrencegeometry'),
        ),
        migrations.AlterUniqueTogether(
            name='occurrencetenure',
            unique_together={('occurrence_geometry', 'tenure_area_id', 'status')},
        ),
    ]
