# Generated by Django 3.2.25 on 2024-06-04 03:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0276_merge_20240604_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='district',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='region',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
    ]
