# Generated by Django 3.2.25 on 2024-06-04 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0275_merge_0274_auto_20240530_1522_0274_auto_20240531_1355'),
        ('boranga', '0276_remove_occurrence_species_taxonomy'),
    ]

    operations = [
    ]
