# Generated by Django 3.2.25 on 2024-06-04 06:33

import boranga.components.occurrence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0276_auto_20240604_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencetenure',
            name='occurrence_geometry',
            field=models.ForeignKey(blank=True, null=True, on_delete=boranga.components.occurrence.models.SET_NULL_AND_HISTORICAL, related_name='occurrence_tenures', to='boranga.occurrencegeometry'),
        ),
    ]
