# Generated by Django 3.2.25 on 2024-06-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0277_alter_occurrencetenure_occurrence_geometry'),
        ('boranga', '0277_merge_20240604_1056'),
    ]

    operations = [
    ]
