# Generated by Django 3.2.25 on 2024-06-04 05:40

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0277_auto_20240604_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='districts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='regions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.district'),
        ),
        migrations.AlterField(
            model_name='species',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boranga.region'),
        ),
    ]
