# Generated by Django 3.2.25 on 2024-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0280_species_species_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='regions',
        ),
        migrations.AddField(
            model_name='species',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, related_name='species_regions', to='boranga.Region'),
        ),
    ]
