# Generated by Django 3.2.25 on 2024-06-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0278_merge_20240604_1551'),
        ('boranga', '0282_remove_species_species_regions'),
    ]

    operations = [
    ]
