# Generated by Django 3.2.25 on 2024-06-07 06:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0284_alter_species_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='districts',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(9, 'Albany'), (11, 'Blackwood'), (17, 'Central Wheatbelt'), (15, 'Donnelly'), (2, 'East Kimberley'), (10, 'Esperance'), (7, 'Exmouth'), (16, 'Frankland'), (4, 'Geraldton'), (1, 'Goldfields Region'), (5, 'Moora'), (13, 'Perth Hills'), (8, 'Pilbara Region'), (6, 'Shark Bay'), (14, 'Swan Coastal'), (12, 'Wellington'), (3, 'West Kimberley'), (18, 'Wheatbelt Region')], max_length=44, null=True),
        ),
    ]
