# Generated by Django 3.2.25 on 2024-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0285_auto_20240606_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrencetenure',
            options={'verbose_name': 'Occurrence Tenure', 'verbose_name_plural': 'Occurrence Tenures'},
        ),
    ]
