# Generated by Django 3.2.25 on 2024-06-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0285_auto_20240606_1146"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="review_date",
        ),
        migrations.AlterField(
            model_name="conservationstatus",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("with_assessor", "With Assessor"),
                    ("with_referral", "With Referral"),
                    ("with_approver", "With Approver"),
                    ("ready_for_agenda", "Ready For Agenda"),
                    ("awaiting_applicant_respone", "Awaiting Applicant Response"),
                    ("awaiting_assessor_response", "Awaiting Assessor Response"),
                    ("awaiting_responses", "Awaiting Responses"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("discarded", "Discarded"),
                    ("delisted", "DeListed"),
                    ("closed", "Closed"),
                    ("partially_approved", "Partially Approved"),
                    ("partially_declined", "Partially Declined"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
