# Generated by Django 3.2.25 on 2024-06-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0285_alter_species_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='districts',
        ),
        migrations.AddField(
            model_name='species',
            name='districts',
            field=models.ManyToManyField(blank=True, null=True, related_name='species_districts', to='boranga.District'),
        ),
    ]
