# Generated by Django 3.2.25 on 2024-06-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0286_auto_20240607_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='district',
        ),
        migrations.RemoveField(
            model_name='species',
            name='region',
        ),
    ]
