# Generated by Django 3.2.25 on 2024-06-10 06:35

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0287_auto_20240607_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrobserverdetail",
            name="contact",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
