# Generated by Django 3.2.25 on 2024-06-07 06:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0288_auto_20240607_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occhabitatcomposition',
            name='land_form',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (3, 'Test2'), (4, 'Test3'), (5, 'Test4'), (7, 'Test6'), (10, 'Test7')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ocrhabitatcomposition',
            name='land_form',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Test'), (3, 'Test2'), (4, 'Test3'), (5, 'Test4'), (7, 'Test6'), (10, 'Test7')], max_length=250, null=True),
        ),
    ]
