# Generated by Django 3.2.25 on 2024-06-07 07:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0289_auto_20240607_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occhabitatcomposition',
            name='land_form',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ocrhabitatcomposition',
            name='land_form',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=250, null=True),
        ),
    ]
