# Generated by Django 3.2.25 on 2024-06-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0288_merge_0286_auto_20240607_1234_0287_auto_20240607_1602'),
        ('boranga', '0290_auto_20240607_1544'),
    ]

    operations = [
    ]
