# Generated by Django 3.2.25 on 2024-06-10 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0291_merge_20240610_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='occanimalobservation',
            name='copied_ocr_animal_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocranimalobservation'),
        ),
        migrations.AddField(
            model_name='occassociatedspecies',
            name='copied_ocr_associated_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrassociatedspecies'),
        ),
        migrations.AddField(
            model_name='occfirehistory',
            name='copied_ocr_fire_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrfirehistory'),
        ),
        migrations.AddField(
            model_name='occhabitatcomposition',
            name='copied_ocr_habitat_composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrhabitatcomposition'),
        ),
        migrations.AddField(
            model_name='occhabitatcondition',
            name='copied_ocr_habitat_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrhabitatcondition'),
        ),
        migrations.AddField(
            model_name='occidentification',
            name='copied_ocr_identification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocridentification'),
        ),
        migrations.AddField(
            model_name='occlocation',
            name='copied_ocr_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrlocation'),
        ),
        migrations.AddField(
            model_name='occobservationdetail',
            name='copied_ocr_observation_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrobservationdetail'),
        ),
        migrations.AddField(
            model_name='occplantcount',
            name='copied_ocr_plant_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrplantcount'),
        ),
        migrations.AddField(
            model_name='occvegetationstructure',
            name='copied_ocr_vegetation_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.ocrvegetationstructure'),
        ),
    ]
