# Generated by Django 3.2.25 on 2024-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0288_auto_20240610_1435'),
        ('boranga', '0292_auto_20240610_1003'),
    ]

    operations = [
    ]
