# Generated by Django 3.2.25 on 2024-06-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0293_merge_0288_auto_20240610_1435_0292_auto_20240610_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='occassociatedspecies',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ocrassociatedspecies',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='occassociatedspecies',
            name='related_species',
        ),
        migrations.AddField(
            model_name='occassociatedspecies',
            name='related_species',
            field=models.ManyToManyField(to='boranga.Taxonomy'),
        ),
        migrations.RemoveField(
            model_name='ocrassociatedspecies',
            name='related_species',
        ),
        migrations.AddField(
            model_name='ocrassociatedspecies',
            name='related_species',
            field=models.ManyToManyField(to='boranga.Taxonomy'),
        ),
    ]
