# Generated by Django 3.2.25 on 2024-06-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0294_auto_20240611_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occassociatedspecies',
            name='related_species',
            field=models.ManyToManyField(null=True, to='boranga.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='ocrassociatedspecies',
            name='related_species',
            field=models.ManyToManyField(null=True, to='boranga.Taxonomy'),
        ),
    ]
