# Generated by Django 3.2.25 on 2024-06-12 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0295_auto_20240612_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCCContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('organisation', models.CharField(blank=True, max_length=250, null=True)),
                ('main_contact', models.BooleanField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observer_detail', to='boranga.occurrence')),
            ],
            options={
                'unique_together': {('contact_name', 'occurrence')},
            },
        ),
        migrations.DeleteModel(
            name='OCCObserverDetail',
        ),
    ]
