# Generated by Django 3.2.25 on 2024-06-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0295_auto_20240612_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencetenure',
            name='tenure_area_ewkb',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
