# Generated by Django 3.2.25 on 2024-06-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0296_auto_20240612_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occcontactdetail',
            name='occurrence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_detail', to='boranga.occurrence'),
        ),
    ]
