# Generated by Django 3.2.25 on 2024-06-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0296_occurrencetenure_tenure_area_ewkb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrencetenurepurpose',
            options={'verbose_name': 'Occurrence Tenure Purpose', 'verbose_name_plural': 'Occurrence Tenure Purposes'},
        ),
    ]
