# Generated by Django 3.2.25 on 2024-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0297_alter_occcontactdetail_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='occcontactdetail',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
