# Generated by Django 3.2.25 on 2024-06-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0298_occcontactdetail_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occassociatedspecies',
            name='related_species',
            field=models.ManyToManyField(blank=True, null=True, to='boranga.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='ocrassociatedspecies',
            name='related_species',
            field=models.ManyToManyField(blank=True, null=True, to='boranga.Taxonomy'),
        ),
    ]
