# Generated by Django 3.2.25 on 2024-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0299_auto_20240612_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occcontactdetail',
            name='main_contact',
        ),
        migrations.AddField(
            model_name='occcontactdetail',
            name='notes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
