# Generated by Django 3.2.25 on 2024-06-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0297_alter_occurrencetenurepurpose_options'),
        ('boranga', '0300_auto_20240612_1539'),
    ]

    operations = [
    ]
