# Generated by Django 3.2.25 on 2024-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0301_merge_20240612_1614"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="iucn_version",
        ),
        migrations.AlterField(
            model_name="occassociatedspecies",
            name="related_species",
            field=models.ManyToManyField(blank=True, to="boranga.Taxonomy"),
        ),
        migrations.AlterField(
            model_name="ocrassociatedspecies",
            name="related_species",
            field=models.ManyToManyField(blank=True, to="boranga.Taxonomy"),
        ),
        migrations.AlterField(
            model_name="species",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="species_regions", to="boranga.Region"
            ),
        ),
        migrations.DeleteModel(
            name="IUCNVersion",
        ),
    ]
