# Generated by Django 3.2.25 on 2024-06-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0301_merge_20240612_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencegeometry',
            name='buffer_radius',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
