# Generated by Django 3.2.25 on 2024-06-14 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0289_merge_20240607_1645'),
        ('boranga', '0301_merge_20240612_1614'),
    ]

    operations = [
    ]
