# Generated by Django 3.2.25 on 2024-06-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0301_merge_20240612_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencereport',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='occurrencereport',
            name='effective_to',
        ),
    ]
