# Generated by Django 3.2.25 on 2024-06-14 03:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0302_occurrencegeometry_buffer_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.5, -35.5, 129.0, -13.5), null=True, srid=4326)),
                ('original_geometry_ewkb', models.BinaryField(blank=True, editable=True, null=True)),
                ('buffered_from_geometry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buffer_geometry', to='boranga.occurrencegeometry')),
            ],
            options={
                'verbose_name': 'Buffer Geometry',
                'verbose_name_plural': 'Buffer Geometries',
            },
        ),
    ]
