# Generated by Django 3.2.25 on 2024-06-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0302_auto_20240613_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencereport',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='occurrencereport',
            name='review_due_date',
        ),
        migrations.RemoveField(
            model_name='occurrencereport',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='occurrencereport',
            name='reviewed_by',
        ),
    ]
