# Generated by Django 3.2.25 on 2024-06-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0303_auto_20240613_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='occurrencereportapprovaldetails',
            name='effective_from_date',
        ),
        migrations.RemoveField(
            model_name='occurrencereportapprovaldetails',
            name='effective_to_date',
        ),
    ]
