# Generated by Django 3.2.25 on 2024-06-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0301_merge_20240612_1614'),
        ('boranga', '0304_auto_20240613_1521'),
    ]

    operations = [
    ]
