# Generated by Django 3.2.25 on 2024-06-17 01:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0305_merge_20240613_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='occurrence_source',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ocr', 'OCR'), ('non-ocr', 'Non-OCR (describe in comments)')], max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='OccurrenceSource',
        ),
    ]
