# Generated by Django 3.2.25 on 2024-06-14 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0303_auto_20240613_1438'),
        ('boranga', '0305_merge_20240613_1617'),
    ]

    operations = [
    ]
