# Generated by Django 3.2.25 on 2024-06-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0302_merge_20240614_0944'),
        ('boranga', '0305_merge_20240613_1617'),
    ]

    operations = [
    ]
