# Generated by Django 3.2.25 on 2024-06-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0303_buffergeometry'),
        ('boranga', '0306_merge_20240614_1623'),
    ]

    operations = [
    ]
