# Generated by Django 3.2.25 on 2024-06-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0301_merge_20240613_1108'),
        ('boranga', '0308_merge_20240617_0951'),
    ]

    operations = [
    ]
