# Generated by Django 3.2.25 on 2024-06-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0306_auto_20240617_0955'),
        ('boranga', '0309_merge_20240617_1403'),
    ]

    operations = [
    ]
