# Generated by Django 3.2.25 on 2024-06-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0310_merge_20240617_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReproductiveMaturity',
            new_name='ReproductiveState',
        ),
        migrations.AlterModelOptions(
            name='reproductivestate',
            options={'ordering': ['name'], 'verbose_name': 'Reproductive State', 'verbose_name_plural': 'Reproductive States'},
        ),
        migrations.RemoveField(
            model_name='occanimalobservation',
            name='reproductive_maturity',
        ),
        migrations.RemoveField(
            model_name='ocranimalobservation',
            name='reproductive_maturity',
        ),
        migrations.AddField(
            model_name='occanimalobservation',
            name='reproductive_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.reproductivestate'),
        ),
        migrations.AddField(
            model_name='ocranimalobservation',
            name='reproductive_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.reproductivestate'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('ready_for_agenda', 'In Meeting'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='conservationstatus',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('ready_for_agenda', 'Ready For Agenda'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('unlocked', 'Unlocked'), ('discarded', 'Discarded'), ('delisted', 'DeListed'), ('closed', 'Closed')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='occanimalobservation',
            name='secondary_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.secondarysign'),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='customer_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'Under Review'), ('with_approver', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('closed', 'DeListed')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_referral', 'With Referral'), ('with_approver', 'With Approver'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('approved', 'Approved'), ('declined', 'Declined'), ('unlocked', 'Unlocked'), ('discarded', 'Discarded'), ('closed', 'DeListed')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='ocranimalobservation',
            name='secondary_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.secondarysign'),
        ),
        migrations.AlterField(
            model_name='species',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, related_name='species_regions', to='boranga.Region'),
        ),
    ]
