# Generated by Django 3.2.25 on 2024-06-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0310_merge_20240617_1628'),
        ('boranga', '0312_auto_20240617_1540'),
    ]

    operations = [
    ]
