# Generated by Django 3.2.25 on 2024-06-18 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0313_merge_20240617_1723"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSExternalRefereeInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("datetime_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "datetime_first_logged_in",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("sent_by", models.IntegerField()),
                ("invite_text", models.TextField(blank=True)),
                ("archived", models.BooleanField(default=False)),
                (
                    "conservation_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_referee_invites",
                        to="boranga.conservationstatus",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Conservation Status Referral Invite",
                "verbose_name_plural": "External Conservation Status Referral Invites",
            },
        ),
    ]
