# Generated by Django 3.2.25 on 2024-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0313_merge_20240617_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='district',
        ),
        migrations.RemoveField(
            model_name='community',
            name='region',
        ),
        migrations.AddField(
            model_name='community',
            name='districts',
            field=models.ManyToManyField(blank=True, null=True, related_name='community_districts', to='boranga.District'),
        ),
        migrations.AddField(
            model_name='community',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, related_name='community_regions', to='boranga.Region'),
        ),
    ]
