# Generated by Django 3.2.25 on 2024-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0314_auto_20240618_0958"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatusreferral",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="species",
            name="districts",
            field=models.ManyToManyField(
                blank=True, related_name="species_districts", to="boranga.District"
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="species_regions", to="boranga.Region"
            ),
        ),
    ]
