# Generated by Django 3.2.25 on 2024-06-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0313_merge_20240618_1553'),
        ('boranga', '0315_auto_20240618_1619'),
    ]

    operations = [
    ]
