# Generated by Django 3.2.25 on 2024-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0315_auto_20240618_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportreferral",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
    ]
