# Generated by Django 3.2.25 on 2024-06-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0314_auto_20240618_1347'),
        ('boranga', '0316_auto_20240619_1012'),
        ('boranga', '0317_auto_20240619_0904'),
    ]

    operations = [
    ]
