# Generated by Django 3.2.25 on 2024-06-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0318_merge_20240619_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="districts",
            field=models.ManyToManyField(
                blank=True, related_name="community_districts", to="boranga.District"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="regions",
            field=models.ManyToManyField(
                blank=True, related_name="community_regions", to="boranga.Region"
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("completed", "Discarded"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
