# Generated by Django 3.2.25 on 2024-06-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0319_auto_20240621_0932"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="visible",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("discarded", "Discarded"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
