# Generated by Django 3.2.25 on 2024-06-20 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('boranga', '0319_auto_20240620_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buffergeometry',
            old_name='copied_from_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='occurrencegeometry',
            old_name='copied_from_id',
            new_name='object_id',
        ),
        migrations.RenameField(
            model_name='occurrencereportgeometry',
            old_name='copied_from_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='buffergeometry',
            name='copied_from_content_type',
        ),
        migrations.RemoveField(
            model_name='occurrencegeometry',
            name='copied_from_content_type',
        ),
        migrations.RemoveField(
            model_name='occurrencereportgeometry',
            name='copied_from_content_type',
        ),
        migrations.AddField(
            model_name='buffergeometry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_buffergeometry', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='occurrencegeometry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_occurrencegeometry', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_occurrencereportgeometry', to='contenttypes.contenttype'),
        ),
    ]
