# Generated by Django 3.2.25 on 2024-06-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0320_auto_20240620_1103'),
        ('boranga', '0320_auto_20240621_1002'),
    ]

    operations = [
    ]
