# Generated by Django 3.2.25 on 2024-06-26 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0322_auto_20240626_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='combined_occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='combined_occurrences', to='boranga.occurrence'),
        ),
    ]
