# Generated by Django 3.2.25 on 2024-06-27 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0323_occurrence_combined_occurrence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occcontactdetail',
            unique_together=set(),
        ),
    ]
