# Generated by Django 3.2.25 on 2024-06-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0324_alter_occcontactdetail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ocrobserverdetail',
            unique_together=set(),
        ),
    ]
