# Generated by Django 3.2.25 on 2024-06-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0325_alter_ocrobserverdetail_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Site Type',
                'verbose_name_plural': 'Site Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OccurrenceSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(blank=True, default='', max_length=9)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('point_coord1', models.FloatField(blank=True, default=0, null=True)),
                ('point_coord2', models.FloatField(blank=True, default=0, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='boranga.occurrence')),
                ('related_occurrence_reports', models.ManyToManyField(blank=True, to='boranga.OccurrenceReport')),
                ('site_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boranga.sitetype')),
            ],
            options={
                'verbose_name': 'Occurrence Site',
            },
        ),
    ]
