# Generated by Django 3.2.25 on 2024-07-01 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0325_alter_ocrobserverdetail_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencetenure',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrencetenure',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
