# Generated by Django 3.2.25 on 2024-06-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0326_occurrencesite_sitetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrencesite',
            unique_together={('occurrence', 'site_name')},
        ),
    ]
