# Generated by Django 3.2.25 on 2024-07-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0327_alter_occurrencesite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencesite',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='occurrencesite',
            unique_together=set(),
        ),
    ]
