# Generated by Django 3.2.25 on 2024-07-01 08:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('boranga', '0328_auto_20240701_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencesite',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_occurrencesite', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='occurrencesite',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, extent=(112.5, -35.5, 129.0, -13.5), null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='occurrencesite',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrencesite',
            name='original_geometry_ewkb',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
