# Generated by Django 3.2.25 on 2024-07-01 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0326_auto_20240701_1035'),
        ('boranga', '0328_auto_20240701_0931'),
    ]

    operations = [
    ]
