# Generated by Django 3.2.25 on 2024-07-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0329_auto_20240701_1634'),
        ('boranga', '0329_merge_0326_auto_20240701_1035_0328_auto_20240701_0931'),
    ]

    operations = [
    ]
