# Generated by Django 3.2.25 on 2024-07-03 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0331_auto_20240702_1430'),
        ('boranga', '0331_auto_20240702_1445'),
    ]

    operations = [
    ]
