# Generated by Django 3.2.25 on 2024-07-04 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0332_auto_20240703_0910'),
        ('boranga', '0332_merge_0331_auto_20240702_1430_0331_auto_20240702_1445'),
    ]

    operations = [
    ]
