# Generated by Django 3.2.25 on 2024-07-04 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0333_occurrencetenurevesting'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencetenure',
            name='vesting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_vestings', to='boranga.occurrencetenurevesting'),
        ),
    ]
