# Generated by Django 3.2.25 on 2024-07-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0334_occurrencetenure_vesting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrencetenurepurpose',
            old_name='purpose',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='occurrencetenurevesting',
            old_name='vesting',
            new_name='name',
        ),
    ]
