# Generated by Django 3.2.25 on 2024-07-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0333_merge_20240704_1001'),
        ('boranga', '0335_auto_20240704_1118'),
    ]

    operations = [
    ]
