# Generated by Django 3.2.25 on 2024-07-04 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0336_merge_20240704_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencetenure',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
