# Generated by Django 3.2.25 on 2024-07-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0334_auto_20240704_1115'),
        ('boranga', '0337_alter_occurrencetenure_datetime_updated'),
    ]

    operations = [
    ]
