# Generated by Django 3.2.25 on 2024-07-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0339_ocrplantcount_plant_count_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrplantcount',
            name='plant_count_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
