# Generated by Django 3.2.25 on 2024-07-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0340_alter_ocrplantcount_plant_count_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='occplantcount',
            name='plant_count_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
