# Generated by Django 3.2.25 on 2024-07-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0341_occplantcount_plant_count_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occplantcount',
            old_name='plant_count_date',
            new_name='count_date',
        ),
        migrations.RenameField(
            model_name='ocrplantcount',
            old_name='plant_count_date',
            new_name='count_date',
        ),
    ]
