# Generated by Django 3.2.25 on 2024-07-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0339_auto_20240708_1344'),
        ('boranga', '0343_auto_20240708_1509'),
    ]

    operations = [
    ]
