# Generated by Django 3.2.25 on 2024-07-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0345_occurrencereportgeometry_show_on_occ_map'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrencereportgeometry',
            old_name='show_on_occ_map',
            new_name='show_on_map',
        ),
    ]
