# Generated by Django 3.2.25 on 2024-07-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0345_auto_20240710_1110'),
        ('boranga', '0346_rename_show_on_occ_map_occurrencereportgeometry_show_on_map'),
    ]

    operations = [
    ]
