# Generated by Django 3.2.25 on 2024-07-12 00:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0347_merge_20240710_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffergeometry',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFF00', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='buffergeometry',
            name='stroke',
            field=colorfield.fields.ColorField(default='#FF9900', image_field=None, max_length=25, samples=None),
        ),
    ]
