# Generated by Django 3.2.25 on 2024-07-12 00:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0349_auto_20240712_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='stroke',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
