# Generated by Django 3.2.25 on 2024-07-15 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0350_auto_20240712_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencegeometry',
            name='opacity',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
