# Generated by Django 3.2.25 on 2024-07-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0351_occurrencegeometry_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencegeometry',
            name='opacity',
        ),
    ]
