# Generated by Django 3.2.25 on 2024-07-15 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0352_remove_occurrencegeometry_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffergeometry',
            name='opacity',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='occurrencegeometry',
            name='opacity',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
