# Generated by Django 3.2.25 on 2024-07-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0355_auto_20240717_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemEmail',
        ),
    ]
