# Generated by Django 3.2.25 on 2024-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0356_auto_20240717_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
