# Generated by Django 3.2.25 on 2024-07-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0357_auto_20240717_1637"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEmailGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("area", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "group_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boranga.grouptype",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SystemEmail",
        ),
    ]
