# Generated by Django 3.2.25 on 2024-07-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0359_auto_20240718_1024"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                (
                    "system_email_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boranga.systememailgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["system_email_group", "email"],
            },
        ),
    ]
