# Generated by Django 3.2.25 on 2024-07-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0355_auto_20240718_1422'),
        ('boranga', '0360_auto_20240718_1031'),
    ]

    operations = [
    ]
