# Generated by Django 3.2.25 on 2024-07-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0360_auto_20240718_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systememailgroup',
            options={'verbose_name': 'System Email Group'},
        ),
        migrations.RenameField(
            model_name='occurrencetenurepurpose',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='occurrencetenurevesting',
            old_name='name',
            new_name='label',
        ),
    ]
