# Generated by Django 3.2.25 on 2024-07-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0361_auto_20240719_0831'),
        ('boranga', '0361_merge_0355_auto_20240718_1422_0360_auto_20240718_1031'),
    ]

    operations = [
    ]
