# Generated by Django 3.2.25 on 2024-07-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0361_merge_0355_auto_20240718_1422_0360_auto_20240718_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systememailgroup',
            options={'verbose_name': 'System Email Group'},
        ),
        migrations.AddField(
            model_name='occanimalobservation',
            name='counted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occplantcount',
            name='counted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocranimalobservation',
            name='counted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ocrplantcount',
            name='counted',
            field=models.BooleanField(default=True),
        ),
    ]
