# Generated by Django 3.2.25 on 2024-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0362_merge_20240719_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencegeometry',
            name='last_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrencereportgeometry',
            name='last_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occurrencesite',
            name='last_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
