# Generated by Django 3.2.25 on 2024-07-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0362_auto_20240719_1506'),
        ('boranga', '0363_auto_20240719_1410'),
    ]

    operations = [
    ]
