# Generated by Django 3.2.25 on 2024-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0364_merge_0362_auto_20240719_1506_0363_auto_20240719_1410"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="proposed_date",
        ),
    ]
