# Generated by Django 3.2.25 on 2024-07-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0365_auto_20240722_1043'),
        ('boranga', '0365_auto_20240722_1335'),
    ]

    operations = [
    ]
