# Generated by Django 3.2.25 on 2024-07-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0365_auto_20240722_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='occhabitatcondition',
            name='count_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocrhabitatcondition',
            name='count_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
