# Generated by Django 3.2.25 on 2024-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0365_fileextensionwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileextensionwhitelist',
            name='model',
            field=models.CharField(default='all', max_length=255),
        ),
    ]
