# Generated by Django 3.2.25 on 2024-07-23 03:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0366_merge_0365_auto_20240722_1043_0365_auto_20240722_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlausibilityGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Plausibility Geometry',
                'verbose_name_plural': 'Plausibility Geometries',
            },
        ),
    ]
