# Generated by Django 3.2.25 on 2024-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0366_alter_fileextensionwhitelist_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileextensionwhitelist',
            name='compressed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
