# Generated by Django 3.2.25 on 2024-07-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0367_plausibilitygeometry'),
    ]

    operations = [
    ]
