# Generated by Django 3.2.25 on 2024-07-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0367_plausibilitygeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='plausibilitygeometry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plausibilitygeometry',
            name='error_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plausibilitygeometry',
            name='warning_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
