# Generated by Django 3.2.25 on 2024-07-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0367_auto_20240723_1140"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemembers",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
