# Generated by Django 3.2.25 on 2024-07-23 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0365_auto_20240722_1335'),
        ('boranga', '0367_fileextensionwhitelist_compressed'),
    ]

    operations = [
    ]
