# Generated by Django 3.2.25 on 2024-07-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0368_auto_20240731_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='plausibilitygeometry',
            name='average_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
