# Generated by Django 3.2.25 on 2024-07-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0368_auto_20240723_1313"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersystemsettings",
            name="event_training_completed",
        ),
        migrations.RemoveField(
            model_name="usersystemsettings",
            name="event_training_date",
        ),
        migrations.AddField(
            model_name="usersystemsettings",
            name="area_of_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.grouptype",
            ),
        ),
    ]
