# Generated by Django 3.2.25 on 2024-08-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0369_plausibilitygeometry_average_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='plausibilitygeometry',
            name='check_for_geometry',
            field=models.CharField(choices=[('OccurrenceGeometry', 'Occurrence-Geometry'), ('OccurrenceReportGeometry', 'Occurrence Report-Geometry')], default='OccurrenceGeometry', max_length=50, verbose_name='Check for Geometry'),
        ),
    ]
