# Generated by Django 3.2.25 on 2024-07-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0368_merge_20240723_0858'),
        ('boranga', '0369_auto_20240723_1637'),
    ]

    operations = [
    ]
