# Generated by Django 3.2.25 on 2024-07-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0366_auto_20240723_1008'),
        ('boranga', '0370_merge_20240724_1530'),
    ]

    operations = [
    ]
