# Generated by Django 3.2.25 on 2024-07-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0372_merge_20240725_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittercategory",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("external", "External"), ("internal", "Internal")],
                max_length=10,
                null=True,
            ),
        ),
    ]
