# Generated by Django 3.2.25 on 2024-07-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0371_merge_20240725_1516'),
        ('boranga', '0372_merge_20240725_1532'),
    ]

    operations = [
    ]
