# Generated by Django 3.2.25 on 2024-07-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0373_auto_20240729_0927"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submittercategory",
            name="user_type",
        ),
        migrations.AddField(
            model_name="submittercategory",
            name="visible_to",
            field=models.CharField(
                choices=[
                    ("external", "External Users"),
                    ("internal", "Internal Users"),
                ],
                default="external",
                max_length=10,
            ),
        ),
    ]
