# Generated by Django 3.2.25 on 2024-07-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0374_auto_20240729_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="datum",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileextensionwhitelist",
            name="compressed",
            field=models.BooleanField(
                help_text="Check this box for extensions such as zip, 7z, and tar"
            ),
        ),
        migrations.AlterField(
            model_name="fileextensionwhitelist",
            name="name",
            field=models.CharField(
                help_text="The file extension without the dot, e.g. jpg, pdf, docx, etc",
                max_length=16,
            ),
        ),
    ]
