# Generated by Django 3.2.25 on 2024-07-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0373_merge_20240725_1625'),
        ('boranga', '0374_auto_20240729_1001'),
    ]

    operations = [
    ]
