# Generated by Django 3.2.25 on 2024-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0375_auto_20240730_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcategory",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
