# Generated by Django 3.2.25 on 2024-07-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0375_merge_20240729_1636'),
        ('boranga', '0376_auto_20240730_1038'),
    ]

    operations = [
    ]
