# Generated by Django 3.2.25 on 2024-07-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0377_merge_20240730_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsubcategory",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
