# Generated by Django 3.2.25 on 2024-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0378_auto_20240730_1220"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildstatus",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
