# Generated by Django 3.2.25 on 2024-07-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0380_auto_20240730_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatagent",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
