# Generated by Django 3.2.25 on 2024-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0381_auto_20240731_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="permittype",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
