# Generated by Django 3.2.25 on 2024-07-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0383_auto_20240731_1117"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencetenurepurpose",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
