# Generated by Django 3.2.25 on 2024-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0387_auto_20240731_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="walegislativecategory",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="waprioritycategory",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
