# Generated by Django 3.2.25 on 2024-08-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0388_auto_20240731_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="migrated_from_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
