# Generated by Django 3.2.25 on 2024-08-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0371_plausibilitygeometry_ratio_effective_area'),
        ('boranga', '0388_auto_20240731_1654'),
    ]

    operations = [
    ]
