# Generated by Django 3.2.25 on 2024-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0389_auto_20240805_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="migrated_from_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
