# Generated by Django 3.2.25 on 2024-08-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0389_merge_20240805_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plausibilitygeometry',
            options={'ordering': ['average_area'], 'verbose_name': 'Plausibility Geometry', 'verbose_name_plural': 'Plausibility Geometries'},
        ),
    ]
