# Generated by Django 3.2.25 on 2024-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0391_auto_20240805_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="soiltype",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
