# Generated by Django 3.2.25 on 2024-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0392_auto_20240805_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="soilcondition",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
