# Generated by Django 3.2.25 on 2024-08-06 03:36

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0393_auto_20240805_1649"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="renamed_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.community",
            ),
        ),
    ]
