# Generated by Django 3.2.25 on 2024-08-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0390_alter_plausibilitygeometry_options'),
        ('boranga', '0394_auto_20240806_1136'),
    ]

    operations = [
    ]
