# Generated by Django 5.0.8 on 2024-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0396_soilcolour_archived_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetype',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
