# Generated by Django 3.2.25 on 2024-08-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0396_auto_20240807_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilelayer',
            name='is_capabilities_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tilelayer',
            name='geoserver_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_layers', to='boranga.geoserverurl'),
        ),
    ]
