# Generated by Django 5.0.8 on 2024-08-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0398_secondarysign_archived_alter_communitydocument__file_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletype',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occurrencegeometry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_%(class)s', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='occurrencereportgeometry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_%(class)s', to='contenttypes.contenttype'),
        ),
    ]
