# Generated by Django 5.0.8 on 2024-08-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0399_sampletype_archived_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sampledestination",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
