# Generated by Django 5.0.8 on 2024-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0400_sampledestination_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootmorphology',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
