# Generated by Django 5.0.8 on 2024-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0401_rootmorphology_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rocktype",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
