# Generated by Django 5.0.8 on 2024-08-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0405_proposalamendmentreason_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarydetectionmethod",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
