# Generated by Django 5.0.8 on 2024-08-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0406_primarydetectionmethod_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialthreatonset",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
