# Generated by Django 3.2.25 on 2024-08-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0397_auto_20240808_1018'),
        ('boranga', '0406_primarydetectionmethod_archived_and_more'),
    ]

    operations = [
    ]
