# Generated by Django 5.0.8 on 2024-08-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0407_potentialthreatonset_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialimpact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
