# Generated by Django 5.0.8 on 2024-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0408_potentialimpact_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postfirehabitatinteraction",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="species",
            name="parent_species",
            field=models.ManyToManyField(blank=True, to="boranga.species"),
        ),
    ]
