# Generated by Django 5.0.8 on 2024-08-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0410_plantcountmethod_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantcountaccuracy",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
