# Generated by Django 5.0.8 on 2024-08-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0411_plantcountaccuracy_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantcondition",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
