# Generated by Django 5.0.8 on 2024-08-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0412_plantcondition_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationmethod",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
