# Generated by Django 5.0.8 on 2024-08-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0416_identificationcertainty_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="florarecruitmenttype",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
