# Generated by Django 5.0.8 on 2024-08-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0417_florarecruitmenttype_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drainage",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
