# Generated by Django 5.0.8 on 2024-08-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0418_drainage_archived_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathreason",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
