# Generated by Django 5.0.8 on 2024-08-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0420_currentimpact_archived_alter_communitydocument__file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="countedsubject",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
