# Generated by Django 5.0.8 on 2024-08-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0407_merge_20240808_1407'),
        ('boranga', '0421_countedsubject_archived_and_more'),
    ]

    operations = [
    ]
