# Generated by Django 5.0.8 on 2024-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0422_merge_20240809_0951"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpTextEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "section_id",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("text", models.TextField()),
                ("icon_with_popover", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Help Text Entries",
            },
        ),
    ]
