# Generated by Django 5.0.8 on 2024-08-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0423_helptextentry_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helptextentry",
            name="authenticated_users_only",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="helptextentry",
            name="internal_users_only",
            field=models.BooleanField(default=True),
        ),
    ]
