# Generated by Django 5.0.8 on 2024-08-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0424_helptextentry_authenticated_users_only_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helptextentry",
            name="icon_with_popover",
            field=models.BooleanField(
                default=False,
                help_text="Instead of showing the text in situ, show a popover with the text",
            ),
        ),
        migrations.AlterField(
            model_name="helptextentry",
            name="section_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
