# Generated by Django 5.0.8 on 2024-08-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0425_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="renamed_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="renamed_to",
                to="boranga.community",
            ),
        ),
    ]
