# Generated by Django 5.0.8 on 2024-08-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0427_alter_community_renamed_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={"verbose_name_plural": "communities"},
        ),
    ]
