# Generated by Django 5.0.8 on 2024-08-15 02:40

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0427_alter_community_renamed_from_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceReportBulkImportTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url="/private-media/",
                            location="/home/oak/dev/boranga/private-media/",
                        ),
                        upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_path,
                    ),
                ),
                ("rows", models.IntegerField(null=True)),
                ("rows_processed", models.IntegerField(default=0)),
                ("datetime_queued", models.DateTimeField(auto_now_add=True)),
                ("datetime_started", models.DateTimeField(blank=True, null=True)),
                ("datetime_completed", models.DateTimeField(blank=True, null=True)),
                ("datetime_error", models.DateTimeField(blank=True, null=True)),
                ("error_row", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("email_user", models.IntegerField()),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Occurrence Report Bulk Import Task",
                "verbose_name_plural": "Occurrence Report Bulk Import Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="community",
            options={"verbose_name_plural": "communities"},
        ),
    ]
