# Generated by Django 5.0.8 on 2024-08-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0428_occurrencereportbulkimporttask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereport",
            name="bulk_import_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrence_reports",
                to="boranga.occurrencereportbulkimporttask",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencereportbulkimporttask",
            name="rows",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
