# Generated by Django 5.0.8 on 2024-08-16 06:14

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0429_occurrencereport_bulk_import_task_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencereport',
            name='import_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='occurrencereportbulkimporttask',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='OccurrenceReportBulkImportSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('group_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.grouptype')),
            ],
            options={
                'verbose_name': 'Occurrence Report Bulk Import Schema',
                'verbose_name_plural': 'Occurrence Report Bulk Import Schemas',
            },
        ),
        migrations.CreateModel(
            name='OccurrenceReportBulkImportSchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_field_name', models.CharField(max_length=50)),
                ('column_header_name', models.CharField(max_length=50)),
                ('data_validation_type', models.CharField(choices=[('textLength', 'textLength'), ('time', 'time'), ('list', 'list'), ('custom', 'custom'), (None, None), ('whole', 'whole'), ('decimal', 'decimal'), ('date', 'date')], default='string', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('list_lookup_field', models.CharField(blank=True, max_length=50, null=True)),
                ('import_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_columns', to='contenttypes.contenttype')),
                ('list_lookup_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_lookup_columns', to='contenttypes.contenttype')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='boranga.occurrencereportbulkimportschema')),
            ],
            options={
                'verbose_name': 'Occurrence Report Bulk Import Schema Column',
                'verbose_name_plural': 'Occurrence Report Bulk Import Schema Columns',
            },
        ),
    ]
