# Generated by Django 5.0.8 on 2024-08-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0430_occurrencereport_import_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimporttask",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="data_validation_type",
            field=models.CharField(
                choices=[
                    ("textLength", "textLength"),
                    ("list", "list"),
                    ("time", "time"),
                    ("date", "date"),
                    ("whole", "whole"),
                    (None, None),
                    ("decimal", "decimal"),
                    ("custom", "custom"),
                ],
                default="string",
                max_length=20,
            ),
        ),
    ]
