# Generated by Django 5.0.8 on 2024-08-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0432_occurrencereportbulkimportschema_datetime_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="schema",
        ),
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="import_content_type",
        ),
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="list_lookup_class",
        ),
        migrations.DeleteModel(
            name="OccurrenceReportBulkImportSchema",
        ),
        migrations.DeleteModel(
            name="OccurrenceReportBulkImportSchemaColumn",
        ),
    ]
