# Generated by Django 5.0.8 on 2024-08-19 03:42

import datetime
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0433_remove_occurrencereportbulkimportschemacolumn_schema_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceReportBulkImportSchema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                (
                    "datetime_updated",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "group_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="boranga.grouptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occurrence Report Bulk Import Schema",
                "verbose_name_plural": "Occurrence Report Bulk Import Schemas",
            },
        ),
        migrations.AddConstraint(
            model_name="occurrencereportbulkimportschema",
            constraint=models.UniqueConstraint(
                fields=("group_type", "version"), name="unique_schema_version"
            ),
        ),
    ]
