# Generated by Django 5.0.8 on 2024-08-19 03:59

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0434_alter_communitydocument__file_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccurrenceReportBulkImportSchemaColumn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("django_import_field_name", models.CharField(max_length=50)),
                ("xlsx_column_header_name", models.CharField(max_length=50)),
                (
                    "xlsx_data_validation_type",
                    models.CharField(
                        choices=[
                            ("custom", "custom"),
                            ("whole", "whole"),
                            (None, None),
                            ("list", "list"),
                            ("time", "time"),
                            ("textLength", "textLength"),
                            ("decimal", "decimal"),
                            ("date", "date"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                (
                    "xlsx_data_validation_allow_blank",
                    models.BooleanField(default=False),
                ),
                (
                    "xlsx_data_validation_operator",
                    models.CharField(
                        choices=[
                            ("lessThan", "lessThan"),
                            ("greaterThan", "greaterThan"),
                            ("greaterThanOrEqual", "greaterThanOrEqual"),
                            ("equal", "equal"),
                            ("notEqual", "notEqual"),
                            ("lessThanOrEqual", "lessThanOrEqual"),
                            ("notBetween", "notBetween"),
                            ("between", "between"),
                            (None, None),
                        ],
                        default="between",
                        max_length=20,
                    ),
                ),
                (
                    "xlsx_data_validation_formula1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "xlsx_data_validation_formula2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "django_import_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_columns",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="boranga.occurrencereportbulkimportschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occurrence Report Bulk Import Schema Column",
                "verbose_name_plural": "Occurrence Report Bulk Import Schema Columns",
            },
        ),
    ]
