# Generated by Django 5.0.8 on 2024-08-19 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0436_alter_occurrencereportbulkimportschema_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimporttask",
            name="schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.occurrencereportbulkimportschema",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="xlsx_data_validation_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("notBetween", "notBetween"),
                    ("lessThan", "lessThan"),
                    ("greaterThan", "greaterThan"),
                    ("between", "between"),
                    ("notEqual", "notEqual"),
                    ("lessThanOrEqual", "lessThanOrEqual"),
                    ("equal", "equal"),
                    ("greaterThanOrEqual", "greaterThanOrEqual"),
                    (None, None),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="xlsx_data_validation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("textLength", "textLength"),
                    ("custom", "custom"),
                    ("decimal", "decimal"),
                    ("whole", "whole"),
                    ("date", "date"),
                    ("list", "list"),
                    ("time", "time"),
                    (None, None),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
