# Generated by Django 5.0.8 on 2024-08-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0429_alter_community_renamed_from_and_more'),
        ('boranga', '0438_alter_communitydocument__file_and_more'),
    ]

    operations = [
    ]
