# Generated by Django 5.0.8 on 2024-09-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0441_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="default_value",
            field=models.CharField(
                blank=True,
                choices=[
                    ("request_user_id", "Request User ID"),
                    ("request_user_email", "Request User Email"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
