# Generated by Django 5.0.8 on 2024-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0442_occurrencereportbulkimportschemacolumn_default_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occurrencereportbulkimportschemacolumn",
            options={
                "ordering": ["schema", "order"],
                "verbose_name": "Occurrence Report Bulk Import Schema Column",
                "verbose_name_plural": "Occurrence Report Bulk Import Schema Columns",
            },
        ),
        migrations.AddField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="default_value",
            field=models.CharField(
                blank=True,
                choices=[("request_user_id", "Request User ID")],
                max_length=255,
                null=True,
            ),
        ),
    ]
