# Generated by Django 5.0.8 on 2024-09-04 06:10

from django.db import migrations


def set_column_order(apps, schema_editor):
    OccurrenceReportBulkImportSchema = apps.get_model(
        "boranga", "OccurrenceReportBulkImportSchema"
    )
    for schema in OccurrenceReportBulkImportSchema.objects.all():
        order_index = 0
        for column in schema.columns.all():
            column.order = order_index
            column.save()
            order_index += 1


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0443_alter_occurrencereportbulkimportschemacolumn_options_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(set_column_order),
    ]
