# Generated by Django 5.0.8 on 2024-09-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0444_auto_20240904_1410"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="prev_processing_status",
        ),
        migrations.RemoveField(
            model_name="occurrencereport",
            name="prev_processing_status",
        ),
        migrations.RemoveField(
            model_name="species",
            name="prev_processing_status",
        ),
    ]
