# Generated by Django 5.0.8 on 2024-09-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0445_remove_community_prev_processing_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitydistribution",
            name="department_file_numbers",
        ),
        migrations.RemoveField(
            model_name="speciesdistribution",
            name="department_file_numbers",
        ),
        migrations.AddField(
            model_name="community",
            name="department_file_numbers",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="species",
            name="department_file_numbers",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
