# Generated by Django 5.0.8 on 2024-09-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0447_remove_communitydistribution_aoo_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytaxonomy',
            name='name_currency',
        ),
    ]
