# Generated by Django 5.0.9 on 2024-09-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0448_remove_communitytaxonomy_name_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencereportreferral",
            name="document",
        ),
    ]
