# Generated by Django 5.0.9 on 2024-09-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0449_remove_occurrencereportreferral_document_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OccurrenceReportReferralDocument",
        ),
    ]
