# Generated by Django 5.0.9 on 2024-09-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0450_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencereportreferral",
            name="referral_text",
        ),
    ]
