# Generated by Django 5.0.9 on 2024-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0451_remove_occurrencereportreferral_referral_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencereportreferral",
            name="sent_from",
        ),
    ]
