# Generated by Django 5.0.9 on 2024-09-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0452_remove_occurrencereportreferral_sent_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrlocation",
            name="boundary",
        ),
    ]
