# Generated by Django 5.0.9 on 2024-09-06 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0454_remove_ocrlocation_new_occurrence_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencegeometry",
            name="intersects",
        ),
        migrations.RemoveField(
            model_name="occurrencereportgeometry",
            name="intersects",
        ),
    ]
