# Generated by Django 5.0.9 on 2024-09-06 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0455_remove_occurrencegeometry_intersects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occlocation",
            name="boundary",
        ),
    ]
