# Generated by Django 5.0.9 on 2024-09-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0456_remove_occlocation_boundary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrence",
            name="review_date",
        ),
        migrations.RemoveField(
            model_name="occurrence",
            name="reviewed_by",
        ),
    ]
