# Generated by Django 5.0.9 on 2024-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0457_remove_occurrence_review_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="django_lookup_field_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
