# Generated by Django 5.0.9 on 2024-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0458_occurrencereportbulkimportschemacolumn_django_lookup_field_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="django_lookup_field_name",
            field=models.CharField(blank=True, default="id", max_length=50, null=True),
        ),
    ]
