# Generated by Django 5.0.9 on 2024-09-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0459_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occlocation",
            name="geojson_point",
        ),
        migrations.RemoveField(
            model_name="occlocation",
            name="geojson_polygon",
        ),
        migrations.RemoveField(
            model_name="ocrlocation",
            name="geojson_point",
        ),
        migrations.RemoveField(
            model_name="ocrlocation",
            name="geojson_polygon",
        ),
    ]
