# Generated by Django 5.0.9 on 2024-09-17 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0460_remove_occlocation_geojson_point_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalSettings",
        ),
    ]
