# Generated by Django 5.0.9 on 2024-09-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0462_remove_conservationstatus_recommended_commonwealth_conservation_list_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="change_date",
        ),
    ]
