# Generated by Django 5.0.9 on 2024-09-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0463_remove_conservationstatus_change_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="recurrence_pattern",
        ),
    ]
