# Generated by Django 5.0.9 on 2024-09-18 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0464_remove_conservationstatus_recurrence_pattern_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="recurrence_schedule",
        ),
    ]
