# Generated by Django 5.0.9 on 2024-09-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0466_remove_conservationstatus_review_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="reviewed_by",
        ),
    ]
