# Generated by Django 5.0.9 on 2024-09-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0467_remove_conservationstatus_reviewed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatusreferral",
            name="document",
        ),
    ]
