# Generated by Django 5.0.9 on 2024-09-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0468_remove_conservationstatusreferral_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatusreferral",
            name="referral_text",
        ),
    ]
