# Generated by Django 5.0.9 on 2024-09-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0469_remove_conservationstatusreferral_referral_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatusreferral",
            name="sent_from",
        ),
    ]
