# Generated by Django 5.0.9 on 2024-09-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0470_remove_conservationstatusreferral_sent_from_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConservationStatusReferralDocument",
        ),
    ]
