# Generated by Django 5.0.9 on 2024-09-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0471_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatusproposalrequest",
            name="officer",
        ),
        migrations.RemoveField(
            model_name="conservationstatusproposalrequest",
            name="subject",
        ),
    ]
