# Generated by Django 5.0.9 on 2024-09-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0472_remove_conservationstatusproposalrequest_officer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="django_lookup_field_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
