# Generated by Django 5.0.9 on 2024-09-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0473_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="migrated_from_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="migrated_from_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
