# Generated by Django 5.0.9 on 2024-09-26 04:22

from django.db import migrations


def set_emtpy_migrated_from_ids_to_null(apps, schema_editor):
    Occurrence = apps.get_model("boranga", "Occurrence")
    occurrences = Occurrence.objects.filter(migrated_from_id="")
    occurrences.update(migrated_from_id=None)
    OccurrenceReport = apps.get_model("boranga", "OccurrenceReport")
    reports = OccurrenceReport.objects.filter(migrated_from_id="")
    reports.update(migrated_from_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0474_alter_communitydocument__file_and_more"),
    ]

    operations = []
