# Generated by Django 5.0.9 on 2024-09-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0476_auto_20240926_1225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="migrated_from_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="migrated_from_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
