# Generated by Django 5.0.9 on 2024-09-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0477_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="xlsx_data_validation_formula1",
        ),
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="xlsx_data_validation_formula2",
        ),
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="xlsx_data_validation_operator",
        ),
        migrations.RemoveField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="xlsx_data_validation_type",
        ),
    ]
