# Generated by Django 5.0.9 on 2024-09-30 08:29

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0478_remove_occurrencereportbulkimportschemacolumn_xlsx_data_validation_formula1_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaColumnLookupFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_field_name", models.CharField(max_length=50)),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("iexact", "Case-insensitive Exact"),
                            ("contains", "Contains"),
                            ("icontains", "Case-insensitive Contains"),
                            ("startswith", "Starts with"),
                            ("istartswith", "Case-insensitive Starts with"),
                            ("endswith", "Ends with"),
                            ("iendswith", "Case-insensitive Ends with"),
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal to"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal to"),
                            ("in", "In"),
                        ],
                        default="exact",
                        max_length=50,
                    ),
                ),
                (
                    "schema_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookup_filters",
                        to="boranga.occurrencereportbulkimportschemacolumn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Column Lookup Filter",
                "verbose_name_plural": "Schema Column Lookup Filters",
            },
        ),
        migrations.CreateModel(
            name="SchemaColumnLookupFilterValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_value", models.CharField(max_length=255)),
                (
                    "lookup_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="boranga.schemacolumnlookupfilter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Column Lookup Filter Value",
                "verbose_name_plural": "Schema Column Lookup Filter Values",
            },
        ),
        migrations.AddConstraint(
            model_name="schemacolumnlookupfilter",
            constraint=models.UniqueConstraint(
                fields=("schema_column", "filter_field_name", "filter_type"),
                name="unique_schema_column_lookup_field",
                violation_error_message="A lookup filter with the same name and type already exists for this schema column",
            ),
        ),
    ]
