# Generated by Django 5.0.9 on 2024-10-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0479_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemacolumnlookupfiltervalue",
            name="filter_value",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
