# Generated by Django 5.0.9 on 2024-10-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0481_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="is_emailuser_column",
            field=models.BooleanField(default=False),
        ),
    ]
