# Generated by Django 5.0.9 on 2024-10-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0483_remove_occurrencereportproposalrequest_officer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimportschema",
            name="is_master",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencereportbulkimportschemacolumn",
            name="is_editable",
            field=models.BooleanField(default=True),
        ),
    ]
