# Generated by Django 5.0.9 on 2024-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0484_occurrencereportbulkimportschema_is_master_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereportbulkimportschema",
            name="datetime_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
