# Generated by Django 5.0.9 on 2024-10-11 01:55

import boranga.components.occurrence.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0485_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportbulkimporttask",
            name="_associated_files_zip",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/private-media/",
                    location="/home/oak/dev/boranga/private-media/",
                ),
                upload_to=boranga.components.occurrence.models.get_occurrence_report_bulk_import_associated_files_path,
                validators=[
                    boranga.components.occurrence.models.validate_bulk_import_associated_files_extension
                ],
            ),
        ),
    ]
