# Generated by Django 5.0.9 on 2024-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0486_occurrencereportbulkimporttask__associated_files_zip_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="cam_mou",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conservationstatus",
            name="cam_mou_date_sent",
            field=models.DateField(blank=True, null=True),
        ),
    ]
