# Generated by Django 5.0.9 on 2024-11-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0487_conservationstatus_cam_mou_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="public_consultation",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="conservationstatus",
            name="public_consultation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conservationstatus",
            name="public_consultation_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
