# Generated by Django 5.0.9 on 2024-11-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0488_conservationstatus_public_consultation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationstatus",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("discarded", "Discarded"),
                    ("with_assessor", "With Assessor"),
                    ("with_referral", "With Referral"),
                    ("deferred", "Deferred"),
                    ("proposed_for_agenda", "Proposed For Agenda"),
                    ("ready_for_agenda", "Ready For Agenda"),
                    ("on_agenda", "On Agenda"),
                    ("with_approver", "Proposed DeListed"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("delisted", "DeListed"),
                    ("closed", "Closed"),
                    ("unlocked", "Unlocked"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("with_assessor", "With Assessor"),
                    ("with_referral", "With Referral"),
                    ("with_approver", "With Approver"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("unlocked", "Unlocked"),
                    ("discarded", "Discarded"),
                    ("closed", "DeListed"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
