# Generated by Django 5.0.9 on 2024-11-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0489_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conservationstatus",
            name="customer_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("with_assessor", "Under Review"),
                    ("ready_for_agenda", "In Meeting"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("discarded", "Discarded"),
                    ("closed", "DeListed"),
                ],
                default="draft",
                max_length=40,
                verbose_name="Customer Status",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencereport",
            name="customer_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("with_assessor", "Under Review"),
                    ("with_approver", "Under Review"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("discarded", "Discarded"),
                    ("closed", "DeListed"),
                ],
                default="draft",
                max_length=40,
                verbose_name="Customer Status",
            ),
        ),
    ]
