# Generated by Django 5.0.9 on 2024-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0490_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commonwealthconservationlist",
            old_name="applies_to_species",
            new_name="applies_to_flora",
        ),
        migrations.RenameField(
            model_name="walegislativelist",
            old_name="applies_to_species",
            new_name="applies_to_flora",
        ),
        migrations.RenameField(
            model_name="waprioritylist",
            old_name="applies_to_species",
            new_name="applies_to_flora",
        ),
        migrations.AddField(
            model_name="commonwealthconservationlist",
            name="applies_to_fauna",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="walegislativelist",
            name="applies_to_fauna",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="waprioritylist",
            name="applies_to_fauna",
            field=models.BooleanField(default=False),
        ),
    ]
