# Generated by Django 5.0.9 on 2024-11-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0491_rename_applies_to_species_commonwealthconservationlist_applies_to_flora_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="conservationstatus",
            old_name="international_conservation",
            new_name="other_conservation_assessment",
        ),
    ]
