# Generated by Django 5.0.9 on 2024-11-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0494_alter_iucnversion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="iucn_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curr_iucn_version",
                to="boranga.iucnversion",
            ),
        ),
    ]
