# Generated by Django 5.0.9 on 2024-11-14 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0496_rename_lodgement_date_meeting_datetime_scheduled_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonwealthconservationlist",
            options={
                "ordering": ["code"],
                "verbose_name": "Commonwealth Conservation Category",
            },
        ),
        migrations.RenameField(
            model_name="conservationstatus",
            old_name="commonwealth_conservation_list",
            new_name="commonwealth_conservation_category",
        ),
    ]
