# Generated by Django 5.0.9 on 2024-11-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0499_occurrencereport_ocr_for_occ_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conservationstatusdocument",
            old_name="visible",
            new_name="active",
        ),
        migrations.RemoveField(
            model_name="conservationstatusdocument",
            name="can_delete",
        ),
        migrations.RemoveField(
            model_name="conservationstatusdocument",
            name="can_hide",
        ),
        migrations.RemoveField(
            model_name="conservationstatusdocument",
            name="hidden",
        ),
    ]
