# Generated by Django 5.0.9 on 2024-11-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0500_rename_visible_conservationstatusdocument_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conservationstatusamendmentrequestdocument",
            old_name="visible",
            new_name="active",
        ),
        migrations.RemoveField(
            model_name="conservationstatusamendmentrequestdocument",
            name="can_delete",
        ),
    ]
