# Generated by Django 5.0.9 on 2024-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0502_rename_visible_communitydocument_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereport",
            name="ocr_for_occ_name",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
