# Generated by Django 5.0.10 on 2025-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0504_rename_last_data_curration_date_community_last_data_curation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conservationstatus',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
