# Generated by Django 5.0.10 on 2025-01-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0505_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherConservationAssessmentList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=512)),
                ("applies_to_flora", models.BooleanField(default=False)),
                ("applies_to_fauna", models.BooleanField(default=False)),
                ("applies_to_communities", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Other Conservation Assessment",
                "ordering": ["code"],
            },
        ),
    ]
