# Generated by Django 5.0.10 on 2025-01-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0506_otherconservationassessmentlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conservationstatus",
            name="other_conservation_assessment",
        ),
    ]
