# Generated by Django 5.0.10 on 2025-01-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0507_remove_conservationstatus_other_conservation_assessment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="other_conservation_assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.otherconservationassessmentlist",
            ),
        ),
    ]
