# Generated by Django 5.0.13 on 2025-03-20 06:58

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0508_conservationstatus_other_conservation_assessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occanimalobservation",
            name="count_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="occplantcount",
            name="count_status",
            field=models.CharField(
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ocranimalobservation",
            name="count_status",
            field=models.CharField(
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ocrplantcount",
            name="count_status",
            field=models.CharField(
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
            ),
        ),
    ]
