# Generated by Django 5.0.13 on 2025-03-20 07:53

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0509_remove_occanimalobservation_counted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occanimalobservation',
            name='counted',
        ),
        migrations.RemoveField(
            model_name='occplantcount',
            name='counted',
        ),
        migrations.RemoveField(
            model_name='ocranimalobservation',
            name='counted',
        ),
        migrations.RemoveField(
            model_name='ocrplantcount',
            name='counted',
        ),
        migrations.AddField(
            model_name='occanimalobservation',
            name='simple_alive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='occanimalobservation',
            name='simple_dead',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ocranimalobservation',
            name='simple_alive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ocranimalobservation',
            name='simple_dead',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='occanimalobservation',
            name='count_status',
            field=models.CharField(choices=[('not_counted', 'Not Counted'), ('detailed_count', 'Detailed Count'), ('simple_count', 'Simple Count')], default='not_counted', max_length=20),
        ),
    ]
