# Generated by Django 5.0.13 on 2025-03-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0510_remove_occanimalobservation_counted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occobservationdetail",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ocrobservationdetail",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
