# Generated by Django 5.0.13 on 2025-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0511_occobservationdetail_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereport",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
