# Generated by Django 5.0.13 on 2025-03-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0512_occurrencereport_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereportapprovaldetails",
            name="copy_ocr_comments_to_occ_comments",
            field=models.BooleanField(default=True),
        ),
    ]
