# Generated by Django 5.0.13 on 2025-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0513_occurrencereportapprovaldetails_copy_ocr_comments_to_occ_comments_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ObserverCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("item", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObserverRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("item", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
