# Generated by Django 5.0.13 on 2025-03-25 07:27

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boranga', '0514_observercategory_observerrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrobserverdetail',
            name='role',
        ),
        migrations.AddField(
            model_name='ocrobserverdetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='boranga.observercategory'),
        ),
    ]
