# Generated by Django 5.0.13 on 2025-03-25 07:35

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0515_remove_ocrobserverdetail_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrobserverdetail",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="boranga.observerrole",
            ),
        ),
    ]
