# Generated by Django 5.0.13 on 2025-03-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "boranga",
            "0516_ocrobserverdetail_role_alter_communitydocument__file_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observercategory",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="observerrole",
            options={"ordering": ["order"]},
        ),
    ]
