# Generated by Django 5.0.13 on 2025-03-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0517_alter_observercategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commonwealthconservationlist",
            options={
                "ordering": ["code"],
                "verbose_name": "Commonwealth Conservation Category",
                "verbose_name_plural": "Commonwealth Conservation Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="observercategory",
            options={
                "ordering": ["order"],
                "verbose_name_plural": "Observer Categories",
            },
        ),
    ]
