# Generated by Django 5.2 on 2025-04-08 05:57

import boranga.components.conservation_status.models
import boranga.components.meetings.models
import boranga.components.occurrence.models
import boranga.components.species_and_communities.models
import boranga.components.users.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0519_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="occurrence_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="occurrence",
            unique_together={
                ("occurrence_name", "community"),
                ("occurrence_name", "species"),
            },
        ),
    ]
