# Generated by Django 5.2 on 2025-04-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0520_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="occurrence",
            unique_together={("occurrence_name", "species", "community")},
        ),
    ]
