# Generated by Django 5.2 on 2025-05-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0522_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datum",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
