# Generated by Django 5.2 on 2025-05-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0523_datum_order_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalhealth",
            options={
                "ordering": ("order",),
                "verbose_name": "Animal Health",
                "verbose_name_plural": "Animal Health",
            },
        ),
        migrations.AlterModelOptions(
            name="coordinatesource",
            options={
                "ordering": ("order",),
                "verbose_name": "Coordinate Source",
                "verbose_name_plural": "Coordinate Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="countedsubject",
            options={
                "ordering": ("order",),
                "verbose_name": "Counted Subject",
                "verbose_name_plural": "Counted Subjects",
            },
        ),
        migrations.AlterModelOptions(
            name="datum",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="deathreason",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="drainage",
            options={
                "ordering": ("order",),
                "verbose_name": "Drainage",
                "verbose_name_plural": "Drainages",
            },
        ),
        migrations.AlterModelOptions(
            name="identificationcertainty",
            options={
                "ordering": ("order",),
                "verbose_name": "Identification Certainty",
                "verbose_name_plural": "Identification Certainties",
            },
        ),
        migrations.AlterModelOptions(
            name="intensity",
            options={
                "ordering": ("order",),
                "verbose_name": "Intensity",
                "verbose_name_plural": "Intensities",
            },
        ),
        migrations.AlterModelOptions(
            name="locationaccuracy",
            options={
                "ordering": ("order",),
                "verbose_name": "Location Accuracy",
                "verbose_name_plural": "Location Accuracy",
            },
        ),
        migrations.AlterModelOptions(
            name="observationmethod",
            options={
                "ordering": ("order",),
                "verbose_name": "Observation Method",
                "verbose_name_plural": "Observation Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="occurrencetenurepurpose",
            options={
                "ordering": ("order",),
                "verbose_name": "Occurrence Tenure Purpose",
                "verbose_name_plural": "Occurrence Tenure Purposes",
            },
        ),
        migrations.AlterModelOptions(
            name="occurrencetenurevesting",
            options={
                "ordering": ("order",),
                "verbose_name": "Occurrence Tenure Vesting",
                "verbose_name_plural": "Occurrence Tenure Vestings",
            },
        ),
        migrations.AlterModelOptions(
            name="permittype",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="plantcondition",
            options={
                "ordering": ("order",),
                "verbose_name": "Plant Condition",
                "verbose_name_plural": "Plant Conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="plantcountaccuracy",
            options={
                "ordering": ("order",),
                "verbose_name": "Plant Count Accuracy",
                "verbose_name_plural": "Plant Count Accuracies",
            },
        ),
        migrations.AlterModelOptions(
            name="plantcountmethod",
            options={
                "ordering": ("order",),
                "verbose_name": "Plant Count Method",
                "verbose_name_plural": "Plant Count Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="primarydetectionmethod",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="reproductivestate",
            options={
                "ordering": ("order",),
                "verbose_name": "Reproductive State",
                "verbose_name_plural": "Reproductive States",
            },
        ),
        migrations.AlterModelOptions(
            name="sampledestination",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="sampletype",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="secondarysign",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="sitetype",
            options={
                "ordering": ("order",),
                "verbose_name": "Site Type",
                "verbose_name_plural": "Site Type",
            },
        ),
        migrations.AlterModelOptions(
            name="soilcolour",
            options={
                "ordering": ("order",),
                "verbose_name": "Soil Colour",
                "verbose_name_plural": "Soil Colours",
            },
        ),
        migrations.AlterModelOptions(
            name="soilcondition",
            options={
                "ordering": ("order",),
                "verbose_name": "Soil Condition",
                "verbose_name_plural": "Soil Conditions",
            },
        ),
        migrations.AlterModelOptions(
            name="soiltype",
            options={
                "ordering": ("order",),
                "verbose_name": "Soil Type",
                "verbose_name_plural": "Soil Types",
            },
        ),
        migrations.AddField(
            model_name="animalhealth",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animalhealth",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coordinatesource",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="countedsubject",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deathreason",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drainage",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="identificationcertainty",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="intensity",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="locationaccuracy",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="observationmethod",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occurrencetenurepurpose",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occurrencetenurevesting",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occurrencetenurevesting",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permittype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantcondition",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantcountaccuracy",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plantcountmethod",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="primarydetectionmethod",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reproductivestate",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sampledestination",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sampletype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondarysign",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitetype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soilcolour",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soilcondition",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="soiltype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wildstatus",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
