# Generated by Django 5.2 on 2025-05-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0524_alter_animalhealth_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committee",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="committeemembers",
            options={
                "ordering": ("order",),
                "verbose_name": "Committee",
                "verbose_name_plural": "Committee Members",
            },
        ),
        migrations.AlterModelOptions(
            name="conservationchangecode",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="currentimpact",
            options={
                "ordering": ("order",),
                "verbose_name": "Current Impact",
                "verbose_name_plural": "Current Impacts",
            },
        ),
        migrations.AlterModelOptions(
            name="documentcategory",
            options={
                "ordering": ("order",),
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="documentsubcategory",
            options={
                "ordering": ("order",),
                "verbose_name": "Document Sub Category",
                "verbose_name_plural": "Document Sub Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="florarecruitmenttype",
            options={
                "ordering": ("order",),
                "verbose_name": "Flora Recruitment Type",
                "verbose_name_plural": "Flora Recruitment Types",
            },
        ),
        migrations.AlterModelOptions(
            name="landform",
            options={
                "ordering": ("order",),
                "verbose_name": "Land Form",
                "verbose_name_plural": "Land Forms",
            },
        ),
        migrations.AlterModelOptions(
            name="postfirehabitatinteraction",
            options={
                "ordering": ("order",),
                "verbose_name": "Post Fire Habitat Interaction",
                "verbose_name_plural": "Post Fire Habitat Interactions",
            },
        ),
        migrations.AlterModelOptions(
            name="potentialimpact",
            options={
                "ordering": ("order",),
                "verbose_name": "Potential Impact",
                "verbose_name_plural": "Potential Impacts",
            },
        ),
        migrations.AlterModelOptions(
            name="potentialthreatonset",
            options={
                "ordering": ("order",),
                "verbose_name": "Potential Threat Onset",
                "verbose_name_plural": "Potential Threat Onsets",
            },
        ),
        migrations.AlterModelOptions(
            name="proposalamendmentreason",
            options={
                "ordering": ("order",),
                "verbose_name": "Proposal Amendment Reason",
                "verbose_name_plural": "Proposal Amendment Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="rocktype",
            options={
                "ordering": ("order",),
                "verbose_name": "Rock Type",
                "verbose_name_plural": "Rock Types",
            },
        ),
        migrations.AlterModelOptions(
            name="rootmorphology",
            options={
                "ordering": ("order",),
                "verbose_name": "Root Morphology",
                "verbose_name_plural": "Root Morphologies",
            },
        ),
        migrations.AlterModelOptions(
            name="submittercategory",
            options={
                "ordering": ("order",),
                "verbose_name_plural": "Submitter Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="threatagent",
            options={
                "ordering": ("order",),
                "verbose_name": "Threat Agent",
                "verbose_name_plural": "Threat Agents",
            },
        ),
        migrations.AlterModelOptions(
            name="threatcategory",
            options={
                "ordering": ("order",),
                "verbose_name": "Threat Category",
                "verbose_name_plural": "Threat Categories",
            },
        ),
        migrations.AddField(
            model_name="committee",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="committeemembers",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commonwealthconservationlist",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conservationchangecode",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currentimpact",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentsubcategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="florarecruitmenttype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iucnversion",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landform",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetingroom",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otherconservationassessmentlist",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postfirehabitatinteraction",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="potentialimpact",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="potentialthreatonset",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proposalamendmentreason",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rocktype",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rootmorphology",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submittercategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threatagent",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threatcategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="walegislativecategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="walegislativelist",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waprioritycategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waprioritylist",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
