# Generated by Django 5.2 on 2025-05-07 06:21

from django.apps import apps
from django.core.management import call_command
from django.db import migrations


def initialise_ordered_models(apps, schema_editor):
    from ordered_model.models import OrderedModel

    app_models = apps.get_app_config("boranga").get_models()
    ordered_models = []
    for model in app_models:
        if issubclass(model, OrderedModel):
            ordered_models.append(model)
    for model in ordered_models:
        call_command(
            "reorder_model",
            model._meta.label,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0525_alter_committee_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            initialise_ordered_models,
        )
    ]
