# Generated by Django 5.2 on 2025-05-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0526_auto_20250507_1421"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permittype",
            options={"ordering": ["group_type", "order"]},
        ),
        migrations.AlterModelOptions(
            name="sampletype",
            options={"ordering": ["group_type", "order"]},
        ),
        migrations.AlterModelOptions(
            name="wildstatus",
            options={
                "ordering": ("order",),
                "verbose_name": "Wild Status",
                "verbose_name_plural": "Wild Statuses",
            },
        ),
    ]
