# Generated by Django 5.2 on 2025-05-08 07:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0527_alter_permittype_options_alter_sampletype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occhabitatcomposition",
            name="soil_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[], max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ocrhabitatcomposition",
            name="soil_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[], max_length=250, null=True
            ),
        ),
    ]
