# Generated by Django 5.2 on 2025-05-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0528_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ocrhabitatcomposition",
            name="soil_type",
        ),
    ]
