# Generated by Django 5.2 on 2025-05-08 08:01

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0529_remove_ocrhabitatcomposition_soil_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrhabitatcomposition",
            name="soil_type",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True, choices=[], max_length=250, null=True
            ),
        ),
    ]
