# Generated by Django 5.2 on 2025-05-09 01:22
from django.apps import apps
from django.db import migrations


def update_show_on_map_to_true(apps, schema_editor):
    OccurrenceReportGeometry = apps.get_model("boranga", "OccurrenceReportGeometry")
    OccurrenceReportGeometry.objects.filter(show_on_map=False).update(show_on_map=True)


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0530_ocrhabitatcomposition_soil_type_and_more"),
    ]

    operations = [
        migrations.RunPython(update_show_on_map_to_true),
    ]
