# Generated by Django 5.2 on 2025-05-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0531_auto_20250509_0922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereportgeometry",
            name="show_on_map",
            field=models.BooleanField(default=True),
        ),
    ]
