# Generated by Django 5.2.1 on 2025-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0532_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occanimalobservation",
            name="count_date",
        ),
        migrations.RemoveField(
            model_name="occhabitatcondition",
            name="count_date",
        ),
        migrations.RemoveField(
            model_name="occplantcount",
            name="count_date",
        ),
        migrations.RemoveField(
            model_name="ocranimalobservation",
            name="count_date",
        ),
        migrations.RemoveField(
            model_name="ocrhabitatcondition",
            name="count_date",
        ),
        migrations.RemoveField(
            model_name="ocrplantcount",
            name="count_date",
        ),
        migrations.AddField(
            model_name="occanimalobservation",
            name="obs_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occhabitatcondition",
            name="obs_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occplantcount",
            name="obs_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocranimalobservation",
            name="obs_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrhabitatcondition",
            name="obs_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrplantcount",
            name="obs_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
