# Generated by Django 5.2.1 on 2025-05-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0533_remove_occanimalobservation_count_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occanimalobservation",
            name="count_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="occplantcount",
            name="count_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ocranimalobservation",
            name="count_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ocrplantcount",
            name="count_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_counted", "Not Counted"),
                    ("detailed_count", "Detailed Count"),
                    ("simple_count", "Simple Count"),
                ],
                default="not_counted",
                max_length=20,
                null=True,
            ),
        ),
    ]
