# Generated by Django 5.2.1 on 2025-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0534_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencereport",
            name="observation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
