# Generated by Django 5.2.1 on 2025-05-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0535_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencereport",
            name="record_source",
            field=models.TextField(blank=True, null=True),
        ),
    ]
