# Generated by Django 5.2.1 on 2025-05-29 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0536_occurrencereport_record_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[,]",
                                code="comma_not_allowed",
                                inverse_match=True,
                                message="Commas not allowed in the display field for a django lookup.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="occurrencereport",
            name="observation_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrence_reports",
                to="boranga.observationtime",
            ),
        ),
    ]
