# Generated by Django 5.2.1 on 2025-06-05 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0537_observationtime_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesListRelatesTo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=250,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "[,]",
                                code="comma_not_allowed",
                                inverse_match=True,
                                message="Commas not allowed in the display field for a django lookup.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Species List Relates To",
                "verbose_name_plural": "Species List Relates To",
                "ordering": ("order",),
                "abstract": False,
            },
        ),
    ]
