# Generated by Django 5.2.1 on 2025-06-05 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boranga", "0538_specieslistrelatesto_alter_communitydocument__file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrassociatedspecies",
            name="species_list_relates_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associated_species",
                to="boranga.specieslistrelatesto",
            ),
        ),
    ]
